/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AttributesEditor.java
 *
 * Created on Dec 7, 2010, 10:09:00 AM
 */
package org.geoimage.viewer.widget;

import java.awt.GridLayout;
import java.sql.Timestamp;
import java.util.Date;
import java.util.HashMap;

import javax.swing.JLabel;
import javax.swing.JTextField;

import org.geoimage.analysis.VDSSchema;
import org.geoimage.viewer.core.layers.AttributesGeometry;

/**
 *
 * @author posadmo
 */
public class AttributesEditor extends javax.swing.JDialog {

    private HashMap<String, Object> map = new HashMap<String, Object>();
    private AttributesGeometry attributes;

    /** Creates new form AttributesEditor */
    public AttributesEditor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public void setAttributes(AttributesGeometry atts) {
        this.attributes = atts;
        ((GridLayout) paramPanel.getLayout()).setRows(atts.getSchema().length);
        for (int i = 0; i < atts.getSchema().length; i++) {
            String att = atts.getSchema()[i];
            Object o=atts.get(att);
            JLabel l = new JLabel(att + " (" + o.getClass().getName() + "):");
            JTextField t = new JTextField("" + o);
            map.put(att, t);
            paramPanel.add(l);
            paramPanel.add(t);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paramPanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        paramPanel.setName("paramPanel"); // NOI18N
        paramPanel.setLayout(new java.awt.GridLayout(5, 2, 2, 2));

        jButton1.setText("OK");
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.setName("jButton2"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(274, 274, 274)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paramPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paramPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      Object[] vals=attributes.getValues();	
      for (int i = 0; i <vals.length ; i++) {
            String att = attributes.getSchema()[i];
            if (map.get(att).toString().equals("null")) {
                continue;
            }
            //String type = attributes.getTypes()[i];
            Object val=vals[i];
            if (val instanceof Double){//type.equals("Double")) {
                attributes.set(att, (Double)(map.get(att)));
            } else if (val instanceof String){//(type.equals("String")) {
                attributes.set(att, (String)map.get(att));
            } else if(val instanceof Date){//if (type.equals("Date")) {
                attributes.set(att, (Date)map.get(att));
            } else if(val instanceof Timestamp){//if (type.equals("Date")) {
                attributes.set(att, (Timestamp)map.get(att));
            } else if (val instanceof Integer){
                attributes.set(att, (Integer)map.get(att));
            } else if (val instanceof Boolean){
                attributes.set(att, (Boolean)map.get(att));
            }else if (val instanceof double[]){
                attributes.set(att, (Double)map.get(att));
            }
        }
        setVisible(false);
        this.getOwner().dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        setVisible(false);
        this.getOwner().dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                AttributesEditor dialog = new AttributesEditor(new javax.swing.JFrame(), true);
                AttributesGeometry atts = new AttributesGeometry(VDSSchema.schema);
                dialog.setAttributes(atts);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel paramPanel;
    // End of variables declaration//GEN-END:variables
}
