//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.12 at 02:42:39 PM CEST 
//


package org.geoimage.viewer.core.io.sumoxml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ImId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="image_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="timestampStart" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element ref="{}sensor"/>
 *         &lt;element name="pol" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="polnumeric" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TimeStart" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="TimeStop" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element ref="{}gcps"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "imId",
    "imageName",
    "timestampStart",
    "sensor",
    "pol",
    "polnumeric",
    "timeStart",
    "timeStop",
    "gcps"
})
@XmlRootElement(name = "sat_image_metadata")
public class SatImageMetadata {

    @XmlElement(name = "ImId", required = true)
    protected String imId;
    @XmlElement(name = "image_name", required = true)
    protected String imageName;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar timestampStart;
    @XmlElement(required = true)
    protected String sensor;
    @XmlElement(required = true)
    protected String pol;
    @XmlElement(required = true)
    protected String polnumeric;
    @XmlElement(name = "TimeStart", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar timeStart;
    @XmlElement(name = "TimeStop", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar timeStop;
    @XmlElement(required = true)
    protected Gcps gcps;

    /**
     * Gets the value of the imId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImId() {
        return imId;
    }

    /**
     * Sets the value of the imId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImId(String value) {
        this.imId = value;
    }

    /**
     * Gets the value of the imageName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImageName() {
        return imageName;
    }

    /**
     * Sets the value of the imageName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImageName(String value) {
        this.imageName = value;
    }

    /**
     * Gets the value of the timestampStart property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTimestampStart() {
        return timestampStart;
    }

    /**
     * Sets the value of the timestampStart property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTimestampStart(XMLGregorianCalendar value) {
        this.timestampStart = value;
    }

    /**
     * Gets the value of the sensor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSensor() {
        return sensor;
    }

    /**
     * Sets the value of the sensor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSensor(String value) {
        this.sensor = value;
    }

    /**
     * Gets the value of the pol property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPol() {
        return pol;
    }

    /**
     * Sets the value of the pol property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPol(String value) {
        this.pol = value;
    }

    /**
     * Gets the value of the polnumeric property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPolnumeric() {
        return polnumeric;
    }

    /**
     * Sets the value of the polnumeric property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPolnumeric(String value) {
        this.polnumeric = value;
    }

    /**
     * Gets the value of the timeStart property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTimeStart() {
        return timeStart;
    }

    /**
     * Sets the value of the timeStart property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTimeStart(XMLGregorianCalendar value) {
        this.timeStart = value;
    }

    /**
     * Gets the value of the timeStop property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTimeStop() {
        return timeStop;
    }

    /**
     * Sets the value of the timeStop property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTimeStop(XMLGregorianCalendar value) {
        this.timeStop = value;
    }

    /**
     * Gets the value of the gcps property.
     * 
     * @return
     *     possible object is
     *     {@link Gcps }
     *     
     */
    public Gcps getGcps() {
        return gcps;
    }

    /**
     * Sets the value of the gcps property.
     * 
     * @param value
     *     allowed object is
     *     {@link Gcps }
     *     
     */
    public void setGcps(Gcps value) {
        this.gcps = value;
    }

}
