//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.27 at 05:01:05 PM CEST 
//


package jrc.it.safe.reader.jaxb;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the jrc.it.safe.reader.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _TransmitterReceiverPolarisation_QNAME = new QName("http://www.esa.int/safe/sentinel-1.0/sentinel-1/sar/level-1", "transmitterReceiverPolarisation");
    private final static QName _MissionDataTakeID_QNAME = new QName("http://www.esa.int/safe/sentinel-1.0/sentinel-1/sar/level-1", "missionDataTakeID");
    private final static QName _ProductComposition_QNAME = new QName("http://www.esa.int/safe/sentinel-1.0/sentinel-1/sar/level-1", "productComposition");
    private final static QName _Mode_QNAME = new QName("http://www.esa.int/safe/sentinel-1.0/sentinel-1/sar/level-1", "mode");
    private final static QName _NssdcIdentifier_QNAME = new QName("http://www.esa.int/safe/sentinel-1.0", "nssdcIdentifier");
    private final static QName _ProductType_QNAME = new QName("http://www.esa.int/safe/sentinel-1.0/sentinel-1/sar/level-1", "productType");
    private final static QName _StartTime_QNAME = new QName("http://www.esa.int/safe/sentinel-1.0", "startTime");
    private final static QName _ProductClass_QNAME = new QName("http://www.esa.int/safe/sentinel-1.0/sentinel-1/sar/level-1", "productClass");
    private final static QName _StopTimeANX_QNAME = new QName("http://www.esa.int/safe/sentinel-1.0/sentinel-1", "stopTimeANX");
    private final static QName _Swath_QNAME = new QName("http://www.esa.int/safe/sentinel-1.0/sentinel-1/sar/level-1", "swath");
    private final static QName _PhaseIdentifier_QNAME = new QName("http://www.esa.int/safe/sentinel-1.0", "phaseIdentifier");
    private final static QName _AscendingNodeTime_QNAME = new QName("http://www.esa.int/safe/sentinel-1.0/sentinel-1", "ascendingNodeTime");
    private final static QName _ProductClassDescription_QNAME = new QName("http://www.esa.int/safe/sentinel-1.0/sentinel-1/sar/level-1", "productClassDescription");
    private final static QName _InstrumentConfigurationID_QNAME = new QName("http://www.esa.int/safe/sentinel-1.0/sentinel-1/sar/level-1", "instrumentConfigurationID");
    private final static QName _TotalSlices_QNAME = new QName("http://www.esa.int/safe/sentinel-1.0/sentinel-1/sar/level-1", "totalSlices");
    private final static QName _SegmentStartTime_QNAME = new QName("http://www.esa.int/safe/sentinel-1.0/sentinel-1/sar/level-1", "segmentStartTime");
    private final static QName _SliceProductFlag_QNAME = new QName("http://www.esa.int/safe/sentinel-1.0/sentinel-1/sar/level-1", "sliceProductFlag");
    private final static QName _SliceNumber_QNAME = new QName("http://www.esa.int/safe/sentinel-1.0/sentinel-1/sar/level-1", "sliceNumber");
    private final static QName _StartTimeANX_QNAME = new QName("http://www.esa.int/safe/sentinel-1.0/sentinel-1", "startTimeANX");
    private final static QName _StopTime_QNAME = new QName("http://www.esa.int/safe/sentinel-1.0", "stopTime");
    private final static QName _Coordinates_QNAME = new QName("http://www.opengis.net/gml", "coordinates");
    private final static QName _Number_QNAME = new QName("http://www.esa.int/safe/sentinel-1.0", "number");
    private final static QName _CycleNumber_QNAME = new QName("http://www.esa.int/safe/sentinel-1.0", "cycleNumber");
    private final static QName _ProductTimelinessCategory_QNAME = new QName("http://www.esa.int/safe/sentinel-1.0/sentinel-1/sar/level-1", "productTimelinessCategory");
    private final static QName _Pass_QNAME = new QName("http://www.esa.int/safe/sentinel-1.0/sentinel-1", "pass");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: jrc.it.safe.reader.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link XFDU }
     * 
     */
    public XFDU createXFDU() {
        return new XFDU();
    }

    /**
     * Create an instance of {@link ContentUnit }
     * 
     */
    public ContentUnit createContentUnit() {
        return new ContentUnit();
    }

    /**
     * Create an instance of {@link XFDU.DataObjectSection }
     * 
     */
    public XFDU.DataObjectSection createXFDUDataObjectSection() {
        return new XFDU.DataObjectSection();
    }

    /**
     * Create an instance of {@link XFDU.DataObjectSection.DataObject }
     * 
     */
    public XFDU.DataObjectSection.DataObject createXFDUDataObjectSectionDataObject() {
        return new XFDU.DataObjectSection.DataObject();
    }

    /**
     * Create an instance of {@link XFDU.DataObjectSection.DataObject.ByteStream }
     * 
     */
    public XFDU.DataObjectSection.DataObject.ByteStream createXFDUDataObjectSectionDataObjectByteStream() {
        return new XFDU.DataObjectSection.DataObject.ByteStream();
    }

    /**
     * Create an instance of {@link XFDU.MetadataSection }
     * 
     */
    public XFDU.MetadataSection createXFDUMetadataSection() {
        return new XFDU.MetadataSection();
    }

    /**
     * Create an instance of {@link XFDU.MetadataSection.MetadataObject }
     * 
     */
    public XFDU.MetadataSection.MetadataObject createXFDUMetadataSectionMetadataObject() {
        return new XFDU.MetadataSection.MetadataObject();
    }

    /**
     * Create an instance of {@link XFDU.MetadataSection.MetadataObject.MetadataWrap }
     * 
     */
    public XFDU.MetadataSection.MetadataObject.MetadataWrap createXFDUMetadataSectionMetadataObjectMetadataWrap() {
        return new XFDU.MetadataSection.MetadataObject.MetadataWrap();
    }

    /**
     * Create an instance of {@link Platform }
     * 
     */
    public Platform createPlatform() {
        return new Platform();
    }

    /**
     * Create an instance of {@link FamilyName }
     * 
     */
    public FamilyName createFamilyName() {
        return new FamilyName();
    }

    /**
     * Create an instance of {@link Instrument }
     * 
     */
    public Instrument createInstrument() {
        return new Instrument();
    }

    /**
     * Create an instance of {@link Extension }
     * 
     */
    public Extension createExtension() {
        return new Extension();
    }

    /**
     * Create an instance of {@link OrbitProperties }
     * 
     */
    public OrbitProperties createOrbitProperties() {
        return new OrbitProperties();
    }

    /**
     * Create an instance of {@link TimeANX }
     * 
     */
    public TimeANX createTimeANX() {
        return new TimeANX();
    }

    /**
     * Create an instance of {@link InstrumentMode }
     * 
     */
    public InstrumentMode createInstrumentMode() {
        return new InstrumentMode();
    }

    /**
     * Create an instance of {@link OrbitReference }
     * 
     */
    public OrbitReference createOrbitReference() {
        return new OrbitReference();
    }

    /**
     * Create an instance of {@link OrbitNumber }
     * 
     */
    public OrbitNumber createOrbitNumber() {
        return new OrbitNumber();
    }

    /**
     * Create an instance of {@link RelativeOrbitNumber }
     * 
     */
    public RelativeOrbitNumber createRelativeOrbitNumber() {
        return new RelativeOrbitNumber();
    }

    /**
     * Create an instance of {@link FrameSet }
     * 
     */
    public FrameSet createFrameSet() {
        return new FrameSet();
    }

    /**
     * Create an instance of {@link Frame }
     * 
     */
    public Frame createFrame() {
        return new Frame();
    }

    /**
     * Create an instance of {@link FootPrint }
     * 
     */
    public FootPrint createFootPrint() {
        return new FootPrint();
    }

    /**
     * Create an instance of {@link Resource }
     * 
     */
    public Resource createResource() {
        return new Resource();
    }

    /**
     * Create an instance of {@link Processing }
     * 
     */
    public Processing createProcessing() {
        return new Processing();
    }

    /**
     * Create an instance of {@link Facility }
     * 
     */
    public Facility createFacility() {
        return new Facility();
    }

    /**
     * Create an instance of {@link Software }
     * 
     */
    public Software createSoftware() {
        return new Software();
    }

    /**
     * Create an instance of {@link AcquisitionPeriod }
     * 
     */
    public AcquisitionPeriod createAcquisitionPeriod() {
        return new AcquisitionPeriod();
    }

    /**
     * Create an instance of {@link StandAloneProductInformation }
     * 
     */
    public StandAloneProductInformation createStandAloneProductInformation() {
        return new StandAloneProductInformation();
    }

    /**
     * Create an instance of {@link XFDU.InformationPackageMap }
     * 
     */
    public XFDU.InformationPackageMap createXFDUInformationPackageMap() {
        return new XFDU.InformationPackageMap();
    }

    /**
     * Create an instance of {@link ContentUnit.DataObjectPointer }
     * 
     */
    public ContentUnit.DataObjectPointer createContentUnitDataObjectPointer() {
        return new ContentUnit.DataObjectPointer();
    }

    /**
     * Create an instance of {@link XFDU.DataObjectSection.DataObject.ByteStream.FileLocation }
     * 
     */
    public XFDU.DataObjectSection.DataObject.ByteStream.FileLocation createXFDUDataObjectSectionDataObjectByteStreamFileLocation() {
        return new XFDU.DataObjectSection.DataObject.ByteStream.FileLocation();
    }

    /**
     * Create an instance of {@link XFDU.DataObjectSection.DataObject.ByteStream.Checksum }
     * 
     */
    public XFDU.DataObjectSection.DataObject.ByteStream.Checksum createXFDUDataObjectSectionDataObjectByteStreamChecksum() {
        return new XFDU.DataObjectSection.DataObject.ByteStream.Checksum();
    }

    /**
     * Create an instance of {@link XFDU.MetadataSection.MetadataObject.MetadataReference }
     * 
     */
    public XFDU.MetadataSection.MetadataObject.MetadataReference createXFDUMetadataSectionMetadataObjectMetadataReference() {
        return new XFDU.MetadataSection.MetadataObject.MetadataReference();
    }

    /**
     * Create an instance of {@link XFDU.MetadataSection.MetadataObject.MetadataWrap.XmlData }
     * 
     */
    public XFDU.MetadataSection.MetadataObject.MetadataWrap.XmlData createXFDUMetadataSectionMetadataObjectMetadataWrapXmlData() {
        return new XFDU.MetadataSection.MetadataObject.MetadataWrap.XmlData();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.esa.int/safe/sentinel-1.0/sentinel-1/sar/level-1", name = "transmitterReceiverPolarisation")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createTransmitterReceiverPolarisation(String value) {
        return new JAXBElement<String>(_TransmitterReceiverPolarisation_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.esa.int/safe/sentinel-1.0/sentinel-1/sar/level-1", name = "missionDataTakeID")
    public JAXBElement<BigInteger> createMissionDataTakeID(BigInteger value) {
        return new JAXBElement<BigInteger>(_MissionDataTakeID_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.esa.int/safe/sentinel-1.0/sentinel-1/sar/level-1", name = "productComposition")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createProductComposition(String value) {
        return new JAXBElement<String>(_ProductComposition_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.esa.int/safe/sentinel-1.0/sentinel-1/sar/level-1", name = "mode")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createMode(String value) {
        return new JAXBElement<String>(_Mode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.esa.int/safe/sentinel-1.0", name = "nssdcIdentifier")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createNssdcIdentifier(String value) {
        return new JAXBElement<String>(_NssdcIdentifier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.esa.int/safe/sentinel-1.0/sentinel-1/sar/level-1", name = "productType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createProductType(String value) {
        return new JAXBElement<String>(_ProductType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.esa.int/safe/sentinel-1.0", name = "startTime")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createStartTime(String value) {
        return new JAXBElement<String>(_StartTime_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.esa.int/safe/sentinel-1.0/sentinel-1/sar/level-1", name = "productClass")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createProductClass(String value) {
        return new JAXBElement<String>(_ProductClass_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.esa.int/safe/sentinel-1.0/sentinel-1", name = "stopTimeANX")
    public JAXBElement<Double> createStopTimeANX(Double value) {
        return new JAXBElement<Double>(_StopTimeANX_QNAME, Double.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.esa.int/safe/sentinel-1.0/sentinel-1/sar/level-1", name = "swath")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createSwath(String value) {
        return new JAXBElement<String>(_Swath_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.esa.int/safe/sentinel-1.0", name = "phaseIdentifier")
    public JAXBElement<BigInteger> createPhaseIdentifier(BigInteger value) {
        return new JAXBElement<BigInteger>(_PhaseIdentifier_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.esa.int/safe/sentinel-1.0/sentinel-1", name = "ascendingNodeTime")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createAscendingNodeTime(String value) {
        return new JAXBElement<String>(_AscendingNodeTime_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.esa.int/safe/sentinel-1.0/sentinel-1/sar/level-1", name = "productClassDescription")
    public JAXBElement<String> createProductClassDescription(String value) {
        return new JAXBElement<String>(_ProductClassDescription_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.esa.int/safe/sentinel-1.0/sentinel-1/sar/level-1", name = "instrumentConfigurationID")
    public JAXBElement<BigInteger> createInstrumentConfigurationID(BigInteger value) {
        return new JAXBElement<BigInteger>(_InstrumentConfigurationID_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.esa.int/safe/sentinel-1.0/sentinel-1/sar/level-1", name = "totalSlices")
    public JAXBElement<BigInteger> createTotalSlices(BigInteger value) {
        return new JAXBElement<BigInteger>(_TotalSlices_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.esa.int/safe/sentinel-1.0/sentinel-1/sar/level-1", name = "segmentStartTime")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createSegmentStartTime(String value) {
        return new JAXBElement<String>(_SegmentStartTime_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.esa.int/safe/sentinel-1.0/sentinel-1/sar/level-1", name = "sliceProductFlag")
    public JAXBElement<Boolean> createSliceProductFlag(Boolean value) {
        return new JAXBElement<Boolean>(_SliceProductFlag_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.esa.int/safe/sentinel-1.0/sentinel-1/sar/level-1", name = "sliceNumber")
    public JAXBElement<BigInteger> createSliceNumber(BigInteger value) {
        return new JAXBElement<BigInteger>(_SliceNumber_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.esa.int/safe/sentinel-1.0/sentinel-1", name = "startTimeANX")
    public JAXBElement<Double> createStartTimeANX(Double value) {
        return new JAXBElement<Double>(_StartTimeANX_QNAME, Double.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.esa.int/safe/sentinel-1.0", name = "stopTime")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createStopTime(String value) {
        return new JAXBElement<String>(_StopTime_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/gml", name = "coordinates")
    public JAXBElement<String> createCoordinates(String value) {
        return new JAXBElement<String>(_Coordinates_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.esa.int/safe/sentinel-1.0", name = "number")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createNumber(String value) {
        return new JAXBElement<String>(_Number_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.esa.int/safe/sentinel-1.0", name = "cycleNumber")
    public JAXBElement<BigInteger> createCycleNumber(BigInteger value) {
        return new JAXBElement<BigInteger>(_CycleNumber_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.esa.int/safe/sentinel-1.0/sentinel-1/sar/level-1", name = "productTimelinessCategory")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createProductTimelinessCategory(String value) {
        return new JAXBElement<String>(_ProductTimelinessCategory_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.esa.int/safe/sentinel-1.0/sentinel-1", name = "pass")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createPass(String value) {
        return new JAXBElement<String>(_Pass_QNAME, String.class, null, value);
    }

}
