//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.24 at 04:43:09 PM CEST 
//


package jrc.it.annotation.reader.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}azimuthTime"/>
 *         &lt;element ref="{}t0"/>
 *         &lt;element ref="{}geometryDcPolynomial"/>
 *         &lt;element ref="{}dataDcPolynomial"/>
 *         &lt;element ref="{}dataDcRmsError"/>
 *         &lt;element ref="{}dataDcRmsErrorAboveThreshold"/>
 *         &lt;element ref="{}fineDceAzimuthStartTime"/>
 *         &lt;element ref="{}fineDceAzimuthStopTime"/>
 *         &lt;element ref="{}fineDceList"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "azimuthTime",
    "t0",
    "geometryDcPolynomial",
    "dataDcPolynomial",
    "dataDcRmsError",
    "dataDcRmsErrorAboveThreshold",
    "fineDceAzimuthStartTime",
    "fineDceAzimuthStopTime",
    "fineDceList"
})
@XmlRootElement(name = "dcEstimate")
public class DcEstimate {

    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String azimuthTime;
    protected double t0;
    @XmlElement(required = true)
    protected GeometryDcPolynomial geometryDcPolynomial;
    @XmlElement(required = true)
    protected DataDcPolynomial dataDcPolynomial;
    protected double dataDcRmsError;
    protected boolean dataDcRmsErrorAboveThreshold;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String fineDceAzimuthStartTime;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String fineDceAzimuthStopTime;
    @XmlElement(required = true)
    protected FineDceList fineDceList;

    /**
     * Gets the value of the azimuthTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAzimuthTime() {
        return azimuthTime;
    }

    /**
     * Sets the value of the azimuthTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAzimuthTime(String value) {
        this.azimuthTime = value;
    }

    /**
     * Gets the value of the t0 property.
     * 
     */
    public double getT0() {
        return t0;
    }

    /**
     * Sets the value of the t0 property.
     * 
     */
    public void setT0(double value) {
        this.t0 = value;
    }

    /**
     * Gets the value of the geometryDcPolynomial property.
     * 
     * @return
     *     possible object is
     *     {@link GeometryDcPolynomial }
     *     
     */
    public GeometryDcPolynomial getGeometryDcPolynomial() {
        return geometryDcPolynomial;
    }

    /**
     * Sets the value of the geometryDcPolynomial property.
     * 
     * @param value
     *     allowed object is
     *     {@link GeometryDcPolynomial }
     *     
     */
    public void setGeometryDcPolynomial(GeometryDcPolynomial value) {
        this.geometryDcPolynomial = value;
    }

    /**
     * Gets the value of the dataDcPolynomial property.
     * 
     * @return
     *     possible object is
     *     {@link DataDcPolynomial }
     *     
     */
    public DataDcPolynomial getDataDcPolynomial() {
        return dataDcPolynomial;
    }

    /**
     * Sets the value of the dataDcPolynomial property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataDcPolynomial }
     *     
     */
    public void setDataDcPolynomial(DataDcPolynomial value) {
        this.dataDcPolynomial = value;
    }

    /**
     * Gets the value of the dataDcRmsError property.
     * 
     */
    public double getDataDcRmsError() {
        return dataDcRmsError;
    }

    /**
     * Sets the value of the dataDcRmsError property.
     * 
     */
    public void setDataDcRmsError(double value) {
        this.dataDcRmsError = value;
    }

    /**
     * Gets the value of the dataDcRmsErrorAboveThreshold property.
     * 
     */
    public boolean isDataDcRmsErrorAboveThreshold() {
        return dataDcRmsErrorAboveThreshold;
    }

    /**
     * Sets the value of the dataDcRmsErrorAboveThreshold property.
     * 
     */
    public void setDataDcRmsErrorAboveThreshold(boolean value) {
        this.dataDcRmsErrorAboveThreshold = value;
    }

    /**
     * Gets the value of the fineDceAzimuthStartTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFineDceAzimuthStartTime() {
        return fineDceAzimuthStartTime;
    }

    /**
     * Sets the value of the fineDceAzimuthStartTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFineDceAzimuthStartTime(String value) {
        this.fineDceAzimuthStartTime = value;
    }

    /**
     * Gets the value of the fineDceAzimuthStopTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFineDceAzimuthStopTime() {
        return fineDceAzimuthStopTime;
    }

    /**
     * Sets the value of the fineDceAzimuthStopTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFineDceAzimuthStopTime(String value) {
        this.fineDceAzimuthStopTime = value;
    }

    /**
     * Gets the value of the fineDceList property.
     * 
     * @return
     *     possible object is
     *     {@link FineDceList }
     *     
     */
    public FineDceList getFineDceList() {
        return fineDceList;
    }

    /**
     * Sets the value of the fineDceList property.
     * 
     * @param value
     *     allowed object is
     *     {@link FineDceList }
     *     
     */
    public void setFineDceList(FineDceList value) {
        this.fineDceList = value;
    }

}
