//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.24 at 04:43:09 PM CEST 
//


package jrc.it.annotation.reader.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}swath"/>
 *         &lt;element ref="{}rangeProcessing"/>
 *         &lt;element ref="{}azimuthProcessing"/>
 *         &lt;element ref="{}processorScalingFactor"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "swath",
    "rangeProcessing",
    "azimuthProcessing",
    "processorScalingFactor"
})
@XmlRootElement(name = "swathProcParams")
public class SwathProcParams {

    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String swath;
    @XmlElement(required = true)
    protected RangeProcessing rangeProcessing;
    @XmlElement(required = true)
    protected AzimuthProcessing azimuthProcessing;
    protected double processorScalingFactor;

    /**
     * Gets the value of the swath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSwath() {
        return swath;
    }

    /**
     * Sets the value of the swath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSwath(String value) {
        this.swath = value;
    }

    /**
     * Gets the value of the rangeProcessing property.
     * 
     * @return
     *     possible object is
     *     {@link RangeProcessing }
     *     
     */
    public RangeProcessing getRangeProcessing() {
        return rangeProcessing;
    }

    /**
     * Sets the value of the rangeProcessing property.
     * 
     * @param value
     *     allowed object is
     *     {@link RangeProcessing }
     *     
     */
    public void setRangeProcessing(RangeProcessing value) {
        this.rangeProcessing = value;
    }

    /**
     * Gets the value of the azimuthProcessing property.
     * 
     * @return
     *     possible object is
     *     {@link AzimuthProcessing }
     *     
     */
    public AzimuthProcessing getAzimuthProcessing() {
        return azimuthProcessing;
    }

    /**
     * Sets the value of the azimuthProcessing property.
     * 
     * @param value
     *     allowed object is
     *     {@link AzimuthProcessing }
     *     
     */
    public void setAzimuthProcessing(AzimuthProcessing value) {
        this.azimuthProcessing = value;
    }

    /**
     * Gets the value of the processorScalingFactor property.
     * 
     */
    public double getProcessorScalingFactor() {
        return processorScalingFactor;
    }

    /**
     * Sets the value of the processorScalingFactor property.
     * 
     */
    public void setProcessorScalingFactor(double value) {
        this.processorScalingFactor = value;
    }

}
