/*
 * InfoDialog.java
 *
 * Created on April 9, 2008, 4:59 PM
 */
package org.geoimage.viewer.widget.dialog;

import java.awt.Frame;

import javax.swing.SwingUtilities;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import javax.swing.table.DefaultTableModel;

import org.geoimage.viewer.core.layers.visualization.LayerPickedData;
import org.geoimage.viewer.core.wwj.VectorObject;

/**
 *
 * @author  thoorfr
 */
public class InfoDialog extends javax.swing.JDialog {

    private boolean run = true;

    /** Creates new form InfoDialog */
    public InfoDialog(Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Info Dialog");
        LayerPickedData.addListener(new ChangeListener() {

            public void stateChanged(ChangeEvent e) {
                if (!isVisible()) {
                    return;
                }
                VectorObject l = LayerPickedData.getTopObject();
                if (l == null) {
                    SwingUtilities.invokeLater(new Runnable() {

                        public void run() {
                            jTable1.setModel(new DefaultTableModel(0, 0));
                        }
                    });
                    return;
                }
                String[] tempSchema = l.attributes.getSchema();
                final String[] schema = new String[tempSchema.length + 1];
                System.arraycopy(tempSchema, 0, schema, 1, tempSchema.length);
                schema[0] = "Geometry";
                final Object[][] values = new Object[1][schema.length + 1];
                values[0][0] = l.geom;
                for (int i = 1; i < schema.length; i++) {
                    values[0][i] = l.attributes.get(schema[i]);
                }
                SwingUtilities.invokeLater(new Runnable() {
                    public void run() {
                        jTable1.setModel(new DefaultTableModel(
                                values,
                                schema));
                    }
                    });
            }
        });
    }

    @Override
    public void dispose() {
        this.setVisible(false);
        run =
                false;
        super.dispose();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setAlwaysOnTop(true);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
