/*
 * GeometricInteractiveLayerPanel.java
 *
 * Created on June 18, 2008, 5:12 PM
 */

package org.geoimage.viewer.widget.panels;

import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;

import javax.swing.JTable;
import javax.swing.event.ListSelectionEvent;

import org.geoimage.viewer.core.GeometryImage;

/**
 *
 * @author  thoorfr
 */
public class GeometricInteractiveLayerPanel extends javax.swing.JPanel {
    private GeometryImage gl;
    private GeometricLayerModel glm;

    private class jTable extends JTable  implements KeyListener
    {
        @Override
        public void valueChanged(ListSelectionEvent e)
        {
            super.valueChanged(e);
            //((GeometricLayerModel)dataModel).changeSelection(getSelectedRow());
        }
        
        public void keyTyped(KeyEvent e) {
        }

        public void keyPressed(KeyEvent e) {
        }

        public void keyReleased(KeyEvent e) {
            int id = e.getID();
            if(id == e.KEY_RELEASED && e.getKeyChar() == e.VK_BACK_SPACE)
            {
                /*
                if(getSelectedRow() != -1)
                    ((GeometricLayerModel)dataModel).removeSelection(getSelectedRow());
                this.repaint();
                ((GeometricLayerModel)dataModel).changeSelection(getSelectedRow());
                */
            }
        }

    };
        
    /** Creates new form GeometricInteractiveLayerPanel */
    public GeometricInteractiveLayerPanel(GeometryImage glayer) {
        initComponents();
        this.gl=glayer;
        glm=new GeometricLayerModel(gl);
        ((jTable)jTable1).setModel(glm);
        jTable1.addKeyListener((jTable)jTable1);
    }
    
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new jTable();

        setName("Form"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setName("jTable1"); // NOI18N
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

}
