/*
 * SavePanel.java
 *
 * Created on April 3, 2008, 3:55 PM
 */
package org.geoimage.viewer.widget.panels;

import java.awt.Component;
import java.awt.Frame;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.io.File;
import java.io.IOException;
import java.text.NumberFormat;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JFormattedTextField;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JTextField;
import javax.swing.plaf.basic.BasicComboBoxRenderer;
import javax.swing.text.NumberFormatter;

import org.geoimage.viewer.common.OptionMenu;
import org.geoimage.viewer.core.SumoPlatform;
import org.geoimage.viewer.core.api.ILayer;
import org.geoimage.viewer.core.api.ISave;
import org.geoimage.viewer.core.gui.manager.LayerManager;
import org.geoimage.viewer.core.layers.image.ImageLayer;
import org.geoimage.viewer.core.layers.visualization.vectors.ComplexEditVDSVectorLayer;
import org.geoimage.viewer.core.layers.visualization.vectors.MaskVectorLayer;
import org.geotools.referencing.CRS;
import org.slf4j.LoggerFactory;



/**
 *
 * @author  thoorfr
 */
public class SavePanel extends javax.swing.JPanel {

	class ItemRenderer extends BasicComboBoxRenderer{
    	ItemRenderer(){
    		super();
    	}
    	@Override
    	 public Component getListCellRendererComponent(
    	            JList list, Object value, int index,
    	            boolean isSelected, boolean cellHasFocus){
    	            
    				super.getListCellRendererComponent(list, value, index,isSelected, cellHasFocus);
    				if(value instanceof OptionMenu){
	    	            if (value != null) {
	    	            	OptionMenu item = (OptionMenu)value;
	    	                setText( item.getOptionDesc());
	    	            }
	    	 
	    	            if (index == -1){
	    	            	OptionMenu item = (OptionMenu)value;
	    	            	setText( item.getOptionDesc());
	    	            }
    				}    
    	            return this;
    	        }
	}
	
	private static org.slf4j.Logger logger=LoggerFactory.getLogger(SavePanel.class);

    private ISave saveLayer;
    private String epsg="4326";

    /** Creates new form SavePanel */
    public SavePanel(ISave layer) {
        initComponents();
        this.saveLayer = layer;
        
        
        DefaultComboBoxModel<OptionMenu> modelComboFormat=new DefaultComboBoxModel<OptionMenu>(layer.getFileFormatTypes()){
        	@Override
        	public Object getSelectedItem(){
        		return super.getSelectedItem();
        	}
        	
        	@Override
        	public void setSelectedItem(final Object item){
        		super.setSelectedItem(item);
        	}
        };
                
        this.comboSaveFormat.setModel(modelComboFormat);
        this.comboSaveFormat.setRenderer(new ItemRenderer());
        
        this.jComboBox2.setModel(new DefaultComboBoxModel(CRS.getSupportedCodes("EPSG").toArray()));
        this.jComboBox2.getModel().setSelectedItem("4326");
        
        this.jComboBox2.addItemListener(new ItemListener() {
            public void itemStateChanged(ItemEvent e) {
                epsg=(String)comboSaveFormat.getModel().getSelectedItem();
                epsg=epsg.replace("EPSG:", "");
            }
        });
        
        if(layer instanceof MaskVectorLayer)
            if(((MaskVectorLayer)layer).getParent() instanceof ImageLayer){
            	OptionMenu opt=comboSaveFormat.getItemAt(comboSaveFormat.getSelectedIndex());
            	if (opt==null)
            		opt=comboSaveFormat.getItemAt(0);
                jTextField1.setText(((ImageLayer)((MaskVectorLayer)layer).getParent()).getImageReader().getFilesList()[0] + "." + opt.getOptionDesc());
            }
        
        if(layer instanceof ComplexEditVDSVectorLayer){
        	labelRunVersion.setVisible(true);
        	labelRunVersionNumber.setVisible(true);
        	txtRunVersion.setVisible(true);
        	txtRunVersionNumber.setVisible(true);
        }else{
        	labelRunVersion.setVisible(false);
        	labelRunVersionNumber.setVisible(false);
        	txtRunVersion.setVisible(false);
        	txtRunVersionNumber.setVisible(false);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        comboSaveFormat = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        labelRunVersion = new javax.swing.JLabel();
        labelRunVersionNumber=new JLabel();
        txtRunVersion=new JTextField();
        
        jTextField1.setText(SumoPlatform.getApplication().getCurrentImageReader().getImId());
        
        NumberFormat format = NumberFormat.getInstance();
        NumberFormatter formatter = new NumberFormatter(format);
        formatter.setValueClass(Integer.class);
        formatter.setMinimum(0);
        formatter.setMaximum(Integer.MAX_VALUE);
        // If you want the value to be committed on each keystroke instead of focus lost
        formatter.setCommitsOnValidEdit(true);
        
        txtRunVersionNumber=new JFormattedTextField(formatter);
        txtRunVersionNumber.setValue(new Integer(1));
        
        setName("Save"); // NOI18N

        jLabel1.setText("File:");

        jButton1.setText("Choose");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Type:");

        comboSaveFormat.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboSaveFormat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        
        labelRunVersion.setText("Run version :");
        
        labelRunVersionNumber.setText("Run version Number:");
        
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("Projection:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(labelRunVersion)
                            .addComponent(labelRunVersionNumber))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE))
                            .addComponent(jComboBox2, 0, 329, Short.MAX_VALUE)
                            .addComponent(comboSaveFormat, 0, 329, Short.MAX_VALUE)
                            .addComponent(txtRunVersion, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                            .addComponent(txtRunVersionNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(314, 314, 314)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(jLabel1))
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(comboSaveFormat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelRunVersion)
                        .addComponent(txtRunVersion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelRunVersionNumber)
                            .addComponent(txtRunVersionNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    	OptionMenu opt=(OptionMenu)comboSaveFormat.getSelectedItem();
    	if(saveLayer instanceof ComplexEditVDSVectorLayer && opt.getOptionId()==ISave.OPT_EXPORT_XML_SUMO ){
    		String runversion=this.txtRunVersion.getText();
    		Integer runId=(Integer)this.txtRunVersionNumber.getValue();
    		((ComplexEditVDSVectorLayer)saveLayer).saveNewXML(jTextField1.getText(),opt.getOptionId() , "EPSG:"+epsg,runversion,runId);
    	}else{
    		saveLayer.save(jTextField1.getText(),opt.getOptionId() , "EPSG:"+epsg);
    	}	
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String filename = null;
        for (ILayer l : LayerManager.getIstanceManager().getLayers().keySet()) {
            if (l instanceof ImageLayer & l.isActive()) {
                filename = ((ImageLayer) l).getName();
                break;
            }
        }
        filename = jTextField1.getText();
        //System.out.println(filename);
        JFileChooser fd = new JFileChooser();
        if(!"".equalsIgnoreCase(filename)&&filename!=null){
        	File f=new File(filename);
        	if(f.getParentFile()!=null && f.getParentFile().exists())
        		fd.setCurrentDirectory(f.getParentFile());
        	
        	fd.setSelectedFile(f);
        }
        int returnVal = fd.showOpenDialog(Frame.getFrames()[0]);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            try {
                jTextField1.setText(fd.getSelectedFile().getCanonicalPath());
            } catch (IOException ex) {
            	logger.error(ex.getMessage(),ex);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
    // remove the previous extension for the file
    String filename = jTextField1.getText();
    int ii=filename.lastIndexOf(".");
    filename = filename.substring(0,ii!=-1?ii:filename.length()-1);
    
    String ext=((OptionMenu)comboSaveFormat.getSelectedItem()).getValue();
    if(!filename.endsWith("."+ext)){
    	filename=filename+"."+ext;
    }    
    jTextField1.setText(filename);
}//GEN-LAST:event_jComboBox1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<OptionMenu> comboSaveFormat;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private JLabel labelRunVersion;
    private JLabel labelRunVersionNumber;
    private javax.swing.JTextField txtRunVersion;
    private javax.swing.JFormattedTextField txtRunVersionNumber;
    
    
    
    // End of variables declaration//GEN-END:variables
}
