//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.27 at 05:01:05 PM CEST 
//


package jrc.it.safe.reader.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.esa.int/safe/sentinel-1.0}footPrint"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "footPrint"
})
@XmlRootElement(name = "frame")
public class Frame {

    @XmlElement(required = true)
    protected FootPrint footPrint;

    /**
     * Gets the value of the footPrint property.
     * 
     * @return
     *     possible object is
     *     {@link FootPrint }
     *     
     */
    public FootPrint getFootPrint() {
        return footPrint;
    }

    /**
     * Sets the value of the footPrint property.
     * 
     * @param value
     *     allowed object is
     *     {@link FootPrint }
     *     
     */
    public void setFootPrint(FootPrint value) {
        this.footPrint = value;
    }

}
