//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.27 at 05:01:05 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.esa.int/safe/sentinel-1.0", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package jrc.it.safe.reader.jaxb;
