//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.27 at 05:01:05 PM CEST 
//


package jrc.it.safe.reader.jaxb;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.esa.int/safe/sentinel-1.0/sentinel-1/sar/level-1}instrumentConfigurationID"/>
 *         &lt;element ref="{http://www.esa.int/safe/sentinel-1.0/sentinel-1/sar/level-1}missionDataTakeID"/>
 *         &lt;element ref="{http://www.esa.int/safe/sentinel-1.0/sentinel-1/sar/level-1}transmitterReceiverPolarisation" maxOccurs="unbounded"/>
 *         &lt;element ref="{http://www.esa.int/safe/sentinel-1.0/sentinel-1/sar/level-1}productClass"/>
 *         &lt;element ref="{http://www.esa.int/safe/sentinel-1.0/sentinel-1/sar/level-1}productClassDescription"/>
 *         &lt;element ref="{http://www.esa.int/safe/sentinel-1.0/sentinel-1/sar/level-1}productComposition"/>
 *         &lt;element ref="{http://www.esa.int/safe/sentinel-1.0/sentinel-1/sar/level-1}productType"/>
 *         &lt;element ref="{http://www.esa.int/safe/sentinel-1.0/sentinel-1/sar/level-1}productTimelinessCategory"/>
 *         &lt;element ref="{http://www.esa.int/safe/sentinel-1.0/sentinel-1/sar/level-1}sliceProductFlag"/>
 *         &lt;element ref="{http://www.esa.int/safe/sentinel-1.0/sentinel-1/sar/level-1}segmentStartTime"/>
 *         &lt;element ref="{http://www.esa.int/safe/sentinel-1.0/sentinel-1/sar/level-1}sliceNumber"/>
 *         &lt;element ref="{http://www.esa.int/safe/sentinel-1.0/sentinel-1/sar/level-1}totalSlices"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "instrumentConfigurationID",
    "missionDataTakeID",
    "transmitterReceiverPolarisation",
    "productClass",
    "productClassDescription",
    "productComposition",
    "productType",
    "productTimelinessCategory",
    "sliceProductFlag",
    "segmentStartTime",
    "sliceNumber",
    "totalSlices"
})
@XmlRootElement(name = "standAloneProductInformation", namespace = "http://www.esa.int/safe/sentinel-1.0/sentinel-1/sar/level-1")
public class StandAloneProductInformation {

    @XmlElement(namespace = "http://www.esa.int/safe/sentinel-1.0/sentinel-1/sar/level-1", required = true)
    protected BigInteger instrumentConfigurationID;
    @XmlElement(namespace = "http://www.esa.int/safe/sentinel-1.0/sentinel-1/sar/level-1", required = true)
    protected BigInteger missionDataTakeID;
    @XmlElement(namespace = "http://www.esa.int/safe/sentinel-1.0/sentinel-1/sar/level-1", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected List<String> transmitterReceiverPolarisation;
    @XmlElement(namespace = "http://www.esa.int/safe/sentinel-1.0/sentinel-1/sar/level-1", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String productClass;
    @XmlElement(namespace = "http://www.esa.int/safe/sentinel-1.0/sentinel-1/sar/level-1", required = true)
    protected String productClassDescription;
    @XmlElement(namespace = "http://www.esa.int/safe/sentinel-1.0/sentinel-1/sar/level-1", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String productComposition;
    @XmlElement(namespace = "http://www.esa.int/safe/sentinel-1.0/sentinel-1/sar/level-1", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String productType;
    @XmlElement(namespace = "http://www.esa.int/safe/sentinel-1.0/sentinel-1/sar/level-1", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String productTimelinessCategory;
    @XmlElement(namespace = "http://www.esa.int/safe/sentinel-1.0/sentinel-1/sar/level-1")
    protected boolean sliceProductFlag;
    @XmlElement(namespace = "http://www.esa.int/safe/sentinel-1.0/sentinel-1/sar/level-1", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String segmentStartTime;
    @XmlElement(namespace = "http://www.esa.int/safe/sentinel-1.0/sentinel-1/sar/level-1", required = true)
    protected BigInteger sliceNumber;
    @XmlElement(namespace = "http://www.esa.int/safe/sentinel-1.0/sentinel-1/sar/level-1", required = true)
    protected BigInteger totalSlices;

    /**
     * Gets the value of the instrumentConfigurationID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getInstrumentConfigurationID() {
        return instrumentConfigurationID;
    }

    /**
     * Sets the value of the instrumentConfigurationID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setInstrumentConfigurationID(BigInteger value) {
        this.instrumentConfigurationID = value;
    }

    /**
     * Gets the value of the missionDataTakeID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMissionDataTakeID() {
        return missionDataTakeID;
    }

    /**
     * Sets the value of the missionDataTakeID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMissionDataTakeID(BigInteger value) {
        this.missionDataTakeID = value;
    }

    /**
     * Gets the value of the transmitterReceiverPolarisation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the transmitterReceiverPolarisation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTransmitterReceiverPolarisation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getTransmitterReceiverPolarisation() {
        if (transmitterReceiverPolarisation == null) {
            transmitterReceiverPolarisation = new ArrayList<String>();
        }
        return this.transmitterReceiverPolarisation;
    }

    /**
     * Gets the value of the productClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductClass() {
        return productClass;
    }

    /**
     * Sets the value of the productClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductClass(String value) {
        this.productClass = value;
    }

    /**
     * Gets the value of the productClassDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductClassDescription() {
        return productClassDescription;
    }

    /**
     * Sets the value of the productClassDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductClassDescription(String value) {
        this.productClassDescription = value;
    }

    /**
     * Gets the value of the productComposition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductComposition() {
        return productComposition;
    }

    /**
     * Sets the value of the productComposition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductComposition(String value) {
        this.productComposition = value;
    }

    /**
     * Gets the value of the productType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductType() {
        return productType;
    }

    /**
     * Sets the value of the productType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductType(String value) {
        this.productType = value;
    }

    /**
     * Gets the value of the productTimelinessCategory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductTimelinessCategory() {
        return productTimelinessCategory;
    }

    /**
     * Sets the value of the productTimelinessCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductTimelinessCategory(String value) {
        this.productTimelinessCategory = value;
    }

    /**
     * Gets the value of the sliceProductFlag property.
     * 
     */
    public boolean isSliceProductFlag() {
        return sliceProductFlag;
    }

    /**
     * Sets the value of the sliceProductFlag property.
     * 
     */
    public void setSliceProductFlag(boolean value) {
        this.sliceProductFlag = value;
    }

    /**
     * Gets the value of the segmentStartTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSegmentStartTime() {
        return segmentStartTime;
    }

    /**
     * Sets the value of the segmentStartTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSegmentStartTime(String value) {
        this.segmentStartTime = value;
    }

    /**
     * Gets the value of the sliceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSliceNumber() {
        return sliceNumber;
    }

    /**
     * Sets the value of the sliceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSliceNumber(BigInteger value) {
        this.sliceNumber = value;
    }

    /**
     * Gets the value of the totalSlices property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTotalSlices() {
        return totalSlices;
    }

    /**
     * Sets the value of the totalSlices property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTotalSlices(BigInteger value) {
        this.totalSlices = value;
    }

}
