//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.05 at 04:36:39 PM CET 
//


package jrc.it.annotation.reader.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Annotation record for Sentinel-1 level 1 general product annotations.
 * 
 * <p>Java class for l1GeneralAnnotationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="l1GeneralAnnotationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="productInformation" type="{}productInformationType"/>
 *         &lt;element name="downlinkInformationList" type="{}downlinkInformationListType"/>
 *         &lt;element name="orbitList" type="{}orbitListType"/>
 *         &lt;element name="attitudeList" type="{}attitudeListType"/>
 *         &lt;element name="rawDataAnalysisList" type="{}rawDataAnalysisListType"/>
 *         &lt;element name="replicaInformationList" type="{}replicaInformationListType"/>
 *         &lt;element name="noiseList" type="{}noiseListType"/>
 *         &lt;element name="terrainHeightList" type="{}terrainHeightListType"/>
 *         &lt;element name="azimuthFmRateList" type="{}azimuthFmRateListType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "l1GeneralAnnotationType", propOrder = {
    "productInformation",
    "downlinkInformationList",
    "orbitList",
    "attitudeList",
    "rawDataAnalysisList",
    "replicaInformationList",
    "noiseList",
    "terrainHeightList",
    "azimuthFmRateList"
})
public class L1GeneralAnnotationType {

    @XmlElement(required = true)
    protected ProductInformationType productInformation;
    @XmlElement(required = true)
    protected DownlinkInformationListType downlinkInformationList;
    @XmlElement(required = true)
    protected OrbitListType orbitList;
    @XmlElement(required = true)
    protected AttitudeListType attitudeList;
    @XmlElement(required = true)
    protected RawDataAnalysisListType rawDataAnalysisList;
    @XmlElement(required = true)
    protected ReplicaInformationListType replicaInformationList;
    @XmlElement(required = true)
    protected NoiseListType noiseList;
    @XmlElement(required = true)
    protected TerrainHeightListType terrainHeightList;
    @XmlElement(required = true)
    protected AzimuthFmRateListType azimuthFmRateList;

    /**
     * Gets the value of the productInformation property.
     * 
     * @return
     *     possible object is
     *     {@link ProductInformationType }
     *     
     */
    public ProductInformationType getProductInformation() {
        return productInformation;
    }

    /**
     * Sets the value of the productInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductInformationType }
     *     
     */
    public void setProductInformation(ProductInformationType value) {
        this.productInformation = value;
    }

    /**
     * Gets the value of the downlinkInformationList property.
     * 
     * @return
     *     possible object is
     *     {@link DownlinkInformationListType }
     *     
     */
    public DownlinkInformationListType getDownlinkInformationList() {
        return downlinkInformationList;
    }

    /**
     * Sets the value of the downlinkInformationList property.
     * 
     * @param value
     *     allowed object is
     *     {@link DownlinkInformationListType }
     *     
     */
    public void setDownlinkInformationList(DownlinkInformationListType value) {
        this.downlinkInformationList = value;
    }

    /**
     * Gets the value of the orbitList property.
     * 
     * @return
     *     possible object is
     *     {@link OrbitListType }
     *     
     */
    public OrbitListType getOrbitList() {
        return orbitList;
    }

    /**
     * Sets the value of the orbitList property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrbitListType }
     *     
     */
    public void setOrbitList(OrbitListType value) {
        this.orbitList = value;
    }

    /**
     * Gets the value of the attitudeList property.
     * 
     * @return
     *     possible object is
     *     {@link AttitudeListType }
     *     
     */
    public AttitudeListType getAttitudeList() {
        return attitudeList;
    }

    /**
     * Sets the value of the attitudeList property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttitudeListType }
     *     
     */
    public void setAttitudeList(AttitudeListType value) {
        this.attitudeList = value;
    }

    /**
     * Gets the value of the rawDataAnalysisList property.
     * 
     * @return
     *     possible object is
     *     {@link RawDataAnalysisListType }
     *     
     */
    public RawDataAnalysisListType getRawDataAnalysisList() {
        return rawDataAnalysisList;
    }

    /**
     * Sets the value of the rawDataAnalysisList property.
     * 
     * @param value
     *     allowed object is
     *     {@link RawDataAnalysisListType }
     *     
     */
    public void setRawDataAnalysisList(RawDataAnalysisListType value) {
        this.rawDataAnalysisList = value;
    }

    /**
     * Gets the value of the replicaInformationList property.
     * 
     * @return
     *     possible object is
     *     {@link ReplicaInformationListType }
     *     
     */
    public ReplicaInformationListType getReplicaInformationList() {
        return replicaInformationList;
    }

    /**
     * Sets the value of the replicaInformationList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReplicaInformationListType }
     *     
     */
    public void setReplicaInformationList(ReplicaInformationListType value) {
        this.replicaInformationList = value;
    }

    /**
     * Gets the value of the noiseList property.
     * 
     * @return
     *     possible object is
     *     {@link NoiseListType }
     *     
     */
    public NoiseListType getNoiseList() {
        return noiseList;
    }

    /**
     * Sets the value of the noiseList property.
     * 
     * @param value
     *     allowed object is
     *     {@link NoiseListType }
     *     
     */
    public void setNoiseList(NoiseListType value) {
        this.noiseList = value;
    }

    /**
     * Gets the value of the terrainHeightList property.
     * 
     * @return
     *     possible object is
     *     {@link TerrainHeightListType }
     *     
     */
    public TerrainHeightListType getTerrainHeightList() {
        return terrainHeightList;
    }

    /**
     * Sets the value of the terrainHeightList property.
     * 
     * @param value
     *     allowed object is
     *     {@link TerrainHeightListType }
     *     
     */
    public void setTerrainHeightList(TerrainHeightListType value) {
        this.terrainHeightList = value;
    }

    /**
     * Gets the value of the azimuthFmRateList property.
     * 
     * @return
     *     possible object is
     *     {@link AzimuthFmRateListType }
     *     
     */
    public AzimuthFmRateListType getAzimuthFmRateList() {
        return azimuthFmRateList;
    }

    /**
     * Sets the value of the azimuthFmRateList property.
     * 
     * @param value
     *     allowed object is
     *     {@link AzimuthFmRateListType }
     *     
     */
    public void setAzimuthFmRateList(AzimuthFmRateListType value) {
        this.azimuthFmRateList = value;
    }

}
