//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.05 at 04:36:39 PM CET 
//


package jrc.it.annotation.reader.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Annotation record for Sentinel-1 level 1 swath timing annotations.
 * 
 * <p>Java class for l1SwathType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="l1SwathType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="linesPerBurst" type="{}uint32"/>
 *         &lt;element name="samplesPerBurst" type="{}uint32"/>
 *         &lt;element name="burstList" type="{}burstListType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "l1SwathType", propOrder = {
    "linesPerBurst",
    "samplesPerBurst",
    "burstList"
})
public class L1SwathType {

    @XmlElement(required = true)
    protected Uint32 linesPerBurst;
    @XmlElement(required = true)
    protected Uint32 samplesPerBurst;
    @XmlElement(required = true)
    protected BurstListType burstList;

    /**
     * Gets the value of the linesPerBurst property.
     * 
     * @return
     *     possible object is
     *     {@link Uint32 }
     *     
     */
    public Uint32 getLinesPerBurst() {
        return linesPerBurst;
    }

    /**
     * Sets the value of the linesPerBurst property.
     * 
     * @param value
     *     allowed object is
     *     {@link Uint32 }
     *     
     */
    public void setLinesPerBurst(Uint32 value) {
        this.linesPerBurst = value;
    }

    /**
     * Gets the value of the samplesPerBurst property.
     * 
     * @return
     *     possible object is
     *     {@link Uint32 }
     *     
     */
    public Uint32 getSamplesPerBurst() {
        return samplesPerBurst;
    }

    /**
     * Sets the value of the samplesPerBurst property.
     * 
     * @param value
     *     allowed object is
     *     {@link Uint32 }
     *     
     */
    public void setSamplesPerBurst(Uint32 value) {
        this.samplesPerBurst = value;
    }

    /**
     * Gets the value of the burstList property.
     * 
     * @return
     *     possible object is
     *     {@link BurstListType }
     *     
     */
    public BurstListType getBurstList() {
        return burstList;
    }

    /**
     * Sets the value of the burstList property.
     * 
     * @param value
     *     allowed object is
     *     {@link BurstListType }
     *     
     */
    public void setBurstList(BurstListType value) {
        this.burstList = value;
    }

}
