//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.05 at 04:36:39 PM CET 
//


package jrc.it.annotation.reader.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Annotation record for processing information.
 * 
 * <p>Java class for processingInformationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="processingInformationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="rawDataAnalysisUsed" type="{}bool"/>
 *         &lt;element name="orbitDataFileUsed" type="{}bool"/>
 *         &lt;element name="attitudeDataFileUsed" type="{}bool"/>
 *         &lt;element name="rxVariationCorrectionApplied" type="{}bool"/>
 *         &lt;element name="antennaElevationPatternApplied" type="{}bool"/>
 *         &lt;element name="antennaAzimuthPatternApplied" type="{}bool"/>
 *         &lt;element name="antennaAzimuthElementPatternApplied" type="{}bool"/>
 *         &lt;element name="dcMethod" type="{}dcMethodType"/>
 *         &lt;element name="dcInputData" type="{}dcInputDataType"/>
 *         &lt;element name="rangeSpreadingLossCompensationApplied" type="{}bool"/>
 *         &lt;element name="srgrConversionApplied" type="{}bool"/>
 *         &lt;element name="detectionPerformed" type="{}bool"/>
 *         &lt;element name="thermalNoiseCorrectionPerformed" type="{}bool"/>
 *         &lt;element name="chirpSource" type="{}chirpSourceType"/>
 *         &lt;element name="pgSource" type="{}pgSourceType"/>
 *         &lt;element name="rrfSpectrum" type="{}rrfSpectrumType"/>
 *         &lt;element name="applicationLutId" type="{}string"/>
 *         &lt;element name="swathProcParamsList" type="{}swathProcParamsListType"/>
 *         &lt;element name="inputDimensionsList" type="{}inputDimensionsListType"/>
 *         &lt;element name="referenceRange" type="{}double"/>
 *         &lt;element name="ellipsoidName" type="{}string"/>
 *         &lt;element name="ellipsoidSemiMajorAxis" type="{}double"/>
 *         &lt;element name="ellipsoidSemiMinorAxis" type="{}double"/>
 *         &lt;element name="bistaticDelayCorrectionApplied" type="{}bool"/>
 *         &lt;element name="topsFilterConvention" type="{}topsFilterConventionType"/>
 *         &lt;element name="orbitSource" type="{}orbitAttitudeSourceType"/>
 *         &lt;element name="attitudeSource" type="{}orbitAttitudeSourceType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "processingInformationType", propOrder = {
    "rawDataAnalysisUsed",
    "orbitDataFileUsed",
    "attitudeDataFileUsed",
    "rxVariationCorrectionApplied",
    "antennaElevationPatternApplied",
    "antennaAzimuthPatternApplied",
    "antennaAzimuthElementPatternApplied",
    "dcMethod",
    "dcInputData",
    "rangeSpreadingLossCompensationApplied",
    "srgrConversionApplied",
    "detectionPerformed",
    "thermalNoiseCorrectionPerformed",
    "chirpSource",
    "pgSource",
    "rrfSpectrum",
    "applicationLutId",
    "swathProcParamsList",
    "inputDimensionsList",
    "referenceRange",
    "ellipsoidName",
    "ellipsoidSemiMajorAxis",
    "ellipsoidSemiMinorAxis",
    "bistaticDelayCorrectionApplied",
    "topsFilterConvention",
    "orbitSource",
    "attitudeSource"
})
public class ProcessingInformationType {

    protected boolean rawDataAnalysisUsed;
    protected boolean orbitDataFileUsed;
    protected boolean attitudeDataFileUsed;
    protected boolean rxVariationCorrectionApplied;
    protected boolean antennaElevationPatternApplied;
    protected boolean antennaAzimuthPatternApplied;
    protected boolean antennaAzimuthElementPatternApplied;
    @XmlElement(required = true)
    protected DcMethodType dcMethod;
    @XmlElement(required = true)
    protected DcInputDataType dcInputData;
    protected boolean rangeSpreadingLossCompensationApplied;
    protected boolean srgrConversionApplied;
    protected boolean detectionPerformed;
    protected boolean thermalNoiseCorrectionPerformed;
    @XmlElement(required = true)
    protected ChirpSourceType chirpSource;
    @XmlElement(required = true)
    protected PgSourceType pgSource;
    @XmlElement(required = true)
    protected RrfSpectrumType rrfSpectrum;
    @XmlElement(required = true)
    protected String applicationLutId;
    @XmlElement(required = true)
    protected SwathProcParamsListType swathProcParamsList;
    @XmlElement(required = true)
    protected InputDimensionsListType inputDimensionsList;
    @XmlElement(required = true)
    protected Double referenceRange;
    @XmlElement(required = true)
    protected String ellipsoidName;
    @XmlElement(required = true)
    protected Double ellipsoidSemiMajorAxis;
    @XmlElement(required = true)
    protected Double ellipsoidSemiMinorAxis;
    protected boolean bistaticDelayCorrectionApplied;
    @XmlElement(required = true)
    protected TopsFilterConventionType topsFilterConvention;
    @XmlElement(required = true)
    protected OrbitAttitudeSourceType orbitSource;
    @XmlElement(required = true)
    protected OrbitAttitudeSourceType attitudeSource;

    /**
     * Gets the value of the rawDataAnalysisUsed property.
     * 
     */
    public boolean isRawDataAnalysisUsed() {
        return rawDataAnalysisUsed;
    }

    /**
     * Sets the value of the rawDataAnalysisUsed property.
     * 
     */
    public void setRawDataAnalysisUsed(boolean value) {
        this.rawDataAnalysisUsed = value;
    }

    /**
     * Gets the value of the orbitDataFileUsed property.
     * 
     */
    public boolean isOrbitDataFileUsed() {
        return orbitDataFileUsed;
    }

    /**
     * Sets the value of the orbitDataFileUsed property.
     * 
     */
    public void setOrbitDataFileUsed(boolean value) {
        this.orbitDataFileUsed = value;
    }

    /**
     * Gets the value of the attitudeDataFileUsed property.
     * 
     */
    public boolean isAttitudeDataFileUsed() {
        return attitudeDataFileUsed;
    }

    /**
     * Sets the value of the attitudeDataFileUsed property.
     * 
     */
    public void setAttitudeDataFileUsed(boolean value) {
        this.attitudeDataFileUsed = value;
    }

    /**
     * Gets the value of the rxVariationCorrectionApplied property.
     * 
     */
    public boolean isRxVariationCorrectionApplied() {
        return rxVariationCorrectionApplied;
    }

    /**
     * Sets the value of the rxVariationCorrectionApplied property.
     * 
     */
    public void setRxVariationCorrectionApplied(boolean value) {
        this.rxVariationCorrectionApplied = value;
    }

    /**
     * Gets the value of the antennaElevationPatternApplied property.
     * 
     */
    public boolean isAntennaElevationPatternApplied() {
        return antennaElevationPatternApplied;
    }

    /**
     * Sets the value of the antennaElevationPatternApplied property.
     * 
     */
    public void setAntennaElevationPatternApplied(boolean value) {
        this.antennaElevationPatternApplied = value;
    }

    /**
     * Gets the value of the antennaAzimuthPatternApplied property.
     * 
     */
    public boolean isAntennaAzimuthPatternApplied() {
        return antennaAzimuthPatternApplied;
    }

    /**
     * Sets the value of the antennaAzimuthPatternApplied property.
     * 
     */
    public void setAntennaAzimuthPatternApplied(boolean value) {
        this.antennaAzimuthPatternApplied = value;
    }

    /**
     * Gets the value of the antennaAzimuthElementPatternApplied property.
     * 
     */
    public boolean isAntennaAzimuthElementPatternApplied() {
        return antennaAzimuthElementPatternApplied;
    }

    /**
     * Sets the value of the antennaAzimuthElementPatternApplied property.
     * 
     */
    public void setAntennaAzimuthElementPatternApplied(boolean value) {
        this.antennaAzimuthElementPatternApplied = value;
    }

    /**
     * Gets the value of the dcMethod property.
     * 
     * @return
     *     possible object is
     *     {@link DcMethodType }
     *     
     */
    public DcMethodType getDcMethod() {
        return dcMethod;
    }

    /**
     * Sets the value of the dcMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link DcMethodType }
     *     
     */
    public void setDcMethod(DcMethodType value) {
        this.dcMethod = value;
    }

    /**
     * Gets the value of the dcInputData property.
     * 
     * @return
     *     possible object is
     *     {@link DcInputDataType }
     *     
     */
    public DcInputDataType getDcInputData() {
        return dcInputData;
    }

    /**
     * Sets the value of the dcInputData property.
     * 
     * @param value
     *     allowed object is
     *     {@link DcInputDataType }
     *     
     */
    public void setDcInputData(DcInputDataType value) {
        this.dcInputData = value;
    }

    /**
     * Gets the value of the rangeSpreadingLossCompensationApplied property.
     * 
     */
    public boolean isRangeSpreadingLossCompensationApplied() {
        return rangeSpreadingLossCompensationApplied;
    }

    /**
     * Sets the value of the rangeSpreadingLossCompensationApplied property.
     * 
     */
    public void setRangeSpreadingLossCompensationApplied(boolean value) {
        this.rangeSpreadingLossCompensationApplied = value;
    }

    /**
     * Gets the value of the srgrConversionApplied property.
     * 
     */
    public boolean isSrgrConversionApplied() {
        return srgrConversionApplied;
    }

    /**
     * Sets the value of the srgrConversionApplied property.
     * 
     */
    public void setSrgrConversionApplied(boolean value) {
        this.srgrConversionApplied = value;
    }

    /**
     * Gets the value of the detectionPerformed property.
     * 
     */
    public boolean isDetectionPerformed() {
        return detectionPerformed;
    }

    /**
     * Sets the value of the detectionPerformed property.
     * 
     */
    public void setDetectionPerformed(boolean value) {
        this.detectionPerformed = value;
    }

    /**
     * Gets the value of the thermalNoiseCorrectionPerformed property.
     * 
     */
    public boolean isThermalNoiseCorrectionPerformed() {
        return thermalNoiseCorrectionPerformed;
    }

    /**
     * Sets the value of the thermalNoiseCorrectionPerformed property.
     * 
     */
    public void setThermalNoiseCorrectionPerformed(boolean value) {
        this.thermalNoiseCorrectionPerformed = value;
    }

    /**
     * Gets the value of the chirpSource property.
     * 
     * @return
     *     possible object is
     *     {@link ChirpSourceType }
     *     
     */
    public ChirpSourceType getChirpSource() {
        return chirpSource;
    }

    /**
     * Sets the value of the chirpSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChirpSourceType }
     *     
     */
    public void setChirpSource(ChirpSourceType value) {
        this.chirpSource = value;
    }

    /**
     * Gets the value of the pgSource property.
     * 
     * @return
     *     possible object is
     *     {@link PgSourceType }
     *     
     */
    public PgSourceType getPgSource() {
        return pgSource;
    }

    /**
     * Sets the value of the pgSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link PgSourceType }
     *     
     */
    public void setPgSource(PgSourceType value) {
        this.pgSource = value;
    }

    /**
     * Gets the value of the rrfSpectrum property.
     * 
     * @return
     *     possible object is
     *     {@link RrfSpectrumType }
     *     
     */
    public RrfSpectrumType getRrfSpectrum() {
        return rrfSpectrum;
    }

    /**
     * Sets the value of the rrfSpectrum property.
     * 
     * @param value
     *     allowed object is
     *     {@link RrfSpectrumType }
     *     
     */
    public void setRrfSpectrum(RrfSpectrumType value) {
        this.rrfSpectrum = value;
    }

    /**
     * Gets the value of the applicationLutId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApplicationLutId() {
        return applicationLutId;
    }

    /**
     * Sets the value of the applicationLutId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApplicationLutId(String value) {
        this.applicationLutId = value;
    }

    /**
     * Gets the value of the swathProcParamsList property.
     * 
     * @return
     *     possible object is
     *     {@link SwathProcParamsListType }
     *     
     */
    public SwathProcParamsListType getSwathProcParamsList() {
        return swathProcParamsList;
    }

    /**
     * Sets the value of the swathProcParamsList property.
     * 
     * @param value
     *     allowed object is
     *     {@link SwathProcParamsListType }
     *     
     */
    public void setSwathProcParamsList(SwathProcParamsListType value) {
        this.swathProcParamsList = value;
    }

    /**
     * Gets the value of the inputDimensionsList property.
     * 
     * @return
     *     possible object is
     *     {@link InputDimensionsListType }
     *     
     */
    public InputDimensionsListType getInputDimensionsList() {
        return inputDimensionsList;
    }

    /**
     * Sets the value of the inputDimensionsList property.
     * 
     * @param value
     *     allowed object is
     *     {@link InputDimensionsListType }
     *     
     */
    public void setInputDimensionsList(InputDimensionsListType value) {
        this.inputDimensionsList = value;
    }

    /**
     * Gets the value of the referenceRange property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getReferenceRange() {
        return referenceRange;
    }

    /**
     * Sets the value of the referenceRange property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setReferenceRange(Double value) {
        this.referenceRange = value;
    }

    /**
     * Gets the value of the ellipsoidName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEllipsoidName() {
        return ellipsoidName;
    }

    /**
     * Sets the value of the ellipsoidName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEllipsoidName(String value) {
        this.ellipsoidName = value;
    }

    /**
     * Gets the value of the ellipsoidSemiMajorAxis property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getEllipsoidSemiMajorAxis() {
        return ellipsoidSemiMajorAxis;
    }

    /**
     * Sets the value of the ellipsoidSemiMajorAxis property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setEllipsoidSemiMajorAxis(Double value) {
        this.ellipsoidSemiMajorAxis = value;
    }

    /**
     * Gets the value of the ellipsoidSemiMinorAxis property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getEllipsoidSemiMinorAxis() {
        return ellipsoidSemiMinorAxis;
    }

    /**
     * Sets the value of the ellipsoidSemiMinorAxis property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setEllipsoidSemiMinorAxis(Double value) {
        this.ellipsoidSemiMinorAxis = value;
    }

    /**
     * Gets the value of the bistaticDelayCorrectionApplied property.
     * 
     */
    public boolean isBistaticDelayCorrectionApplied() {
        return bistaticDelayCorrectionApplied;
    }

    /**
     * Sets the value of the bistaticDelayCorrectionApplied property.
     * 
     */
    public void setBistaticDelayCorrectionApplied(boolean value) {
        this.bistaticDelayCorrectionApplied = value;
    }

    /**
     * Gets the value of the topsFilterConvention property.
     * 
     * @return
     *     possible object is
     *     {@link TopsFilterConventionType }
     *     
     */
    public TopsFilterConventionType getTopsFilterConvention() {
        return topsFilterConvention;
    }

    /**
     * Sets the value of the topsFilterConvention property.
     * 
     * @param value
     *     allowed object is
     *     {@link TopsFilterConventionType }
     *     
     */
    public void setTopsFilterConvention(TopsFilterConventionType value) {
        this.topsFilterConvention = value;
    }

    /**
     * Gets the value of the orbitSource property.
     * 
     * @return
     *     possible object is
     *     {@link OrbitAttitudeSourceType }
     *     
     */
    public OrbitAttitudeSourceType getOrbitSource() {
        return orbitSource;
    }

    /**
     * Sets the value of the orbitSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrbitAttitudeSourceType }
     *     
     */
    public void setOrbitSource(OrbitAttitudeSourceType value) {
        this.orbitSource = value;
    }

    /**
     * Gets the value of the attitudeSource property.
     * 
     * @return
     *     possible object is
     *     {@link OrbitAttitudeSourceType }
     *     
     */
    public OrbitAttitudeSourceType getAttitudeSource() {
        return attitudeSource;
    }

    /**
     * Sets the value of the attitudeSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrbitAttitudeSourceType }
     *     
     */
    public void setAttitudeSource(OrbitAttitudeSourceType value) {
        this.attitudeSource = value;
    }

}
