//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.05 at 04:36:39 PM CET 
//


package jrc.it.annotation.reader.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for productTimelinessCategoryType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="productTimelinessCategoryType">
 *   &lt;restriction base="{}string">
 *     &lt;enumeration value="NRT-10m"/>
 *     &lt;enumeration value="NRT-1h"/>
 *     &lt;enumeration value="NRT-3h"/>
 *     &lt;enumeration value="Fast-24h"/>
 *     &lt;enumeration value="Off-line"/>
 *     &lt;enumeration value="Reprocessing"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "productTimelinessCategoryType")
@XmlEnum
public enum ProductTimelinessCategoryType {

    @XmlEnumValue("NRT-10m")
    NRT_10_M("NRT-10m"),
    @XmlEnumValue("NRT-1h")
    NRT_1_H("NRT-1h"),
    @XmlEnumValue("NRT-3h")
    NRT_3_H("NRT-3h"),
    @XmlEnumValue("Fast-24h")
    FAST_24_H("Fast-24h"),
    @XmlEnumValue("Off-line")
    OFF_LINE("Off-line"),
    @XmlEnumValue("Reprocessing")
    REPROCESSING("Reprocessing");
    private final String value;

    ProductTimelinessCategoryType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ProductTimelinessCategoryType fromValue(String v) {
        for (ProductTimelinessCategoryType c: ProductTimelinessCategoryType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
