//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.05 at 04:36:39 PM CET 
//


package jrc.it.annotation.reader.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for productCompositionType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="productCompositionType">
 *   &lt;restriction base="{}string">
 *     &lt;enumeration value="Individual"/>
 *     &lt;enumeration value="Slice"/>
 *     &lt;enumeration value="Assembled"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "productCompositionType")
@XmlEnum
public enum ProductCompositionType {

    @XmlEnumValue("Individual")
    INDIVIDUAL("Individual"),
    @XmlEnumValue("Slice")
    SLICE("Slice"),
    @XmlEnumValue("Assembled")
    ASSEMBLED("Assembled");
    private final String value;

    ProductCompositionType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ProductCompositionType fromValue(String v) {
        for (ProductCompositionType c: ProductCompositionType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
