//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.24 at 04:43:09 PM CEST 
//


package jrc.it.annotation.reader.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}azimuthTime"/>
 *         &lt;element ref="{}iBias"/>
 *         &lt;element ref="{}qBias"/>
 *         &lt;element ref="{}iqQuadratureDeparture"/>
 *         &lt;element ref="{}iqGainImbalance"/>
 *         &lt;element ref="{}support"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "azimuthTime",
    "iBias",
    "qBias",
    "iqQuadratureDeparture",
    "iqGainImbalance",
    "support"
})
@XmlRootElement(name = "rawDataAnalysis")
public class RawDataAnalysis {

    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String azimuthTime;
    protected double iBias;
    protected double qBias;
    protected double iqQuadratureDeparture;
    protected double iqGainImbalance;
    @XmlElement(required = true)
    protected Support support;

    /**
     * Gets the value of the azimuthTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAzimuthTime() {
        return azimuthTime;
    }

    /**
     * Sets the value of the azimuthTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAzimuthTime(String value) {
        this.azimuthTime = value;
    }

    /**
     * Gets the value of the iBias property.
     * 
     */
    public double getIBias() {
        return iBias;
    }

    /**
     * Sets the value of the iBias property.
     * 
     */
    public void setIBias(double value) {
        this.iBias = value;
    }

    /**
     * Gets the value of the qBias property.
     * 
     */
    public double getQBias() {
        return qBias;
    }

    /**
     * Sets the value of the qBias property.
     * 
     */
    public void setQBias(double value) {
        this.qBias = value;
    }

    /**
     * Gets the value of the iqQuadratureDeparture property.
     * 
     */
    public double getIqQuadratureDeparture() {
        return iqQuadratureDeparture;
    }

    /**
     * Sets the value of the iqQuadratureDeparture property.
     * 
     */
    public void setIqQuadratureDeparture(double value) {
        this.iqQuadratureDeparture = value;
    }

    /**
     * Gets the value of the iqGainImbalance property.
     * 
     */
    public double getIqGainImbalance() {
        return iqGainImbalance;
    }

    /**
     * Sets the value of the iqGainImbalance property.
     * 
     */
    public void setIqGainImbalance(double value) {
        this.iqGainImbalance = value;
    }

    /**
     * Gets the value of the support property.
     * 
     * @return
     *     possible object is
     *     {@link Support }
     *     
     */
    public Support getSupport() {
        return support;
    }

    /**
     * Sets the value of the support property.
     * 
     * @param value
     *     allowed object is
     *     {@link Support }
     *     
     */
    public void setSupport(Support value) {
        this.support = value;
    }

}
