//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.05 at 04:36:39 PM CET 
//


package jrc.it.annotation.reader.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for swathType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="swathType">
 *   &lt;restriction base="{}string">
 *     &lt;enumeration value="S1"/>
 *     &lt;enumeration value="S2"/>
 *     &lt;enumeration value="S3"/>
 *     &lt;enumeration value="S4"/>
 *     &lt;enumeration value="S5"/>
 *     &lt;enumeration value="S6"/>
 *     &lt;enumeration value="IW"/>
 *     &lt;enumeration value="IW1"/>
 *     &lt;enumeration value="IW2"/>
 *     &lt;enumeration value="IW3"/>
 *     &lt;enumeration value="EW"/>
 *     &lt;enumeration value="EW1"/>
 *     &lt;enumeration value="EW2"/>
 *     &lt;enumeration value="EW3"/>
 *     &lt;enumeration value="EW4"/>
 *     &lt;enumeration value="EW5"/>
 *     &lt;enumeration value="WV"/>
 *     &lt;enumeration value="WV1"/>
 *     &lt;enumeration value="WV2"/>
 *     &lt;enumeration value="EN"/>
 *     &lt;enumeration value="N1"/>
 *     &lt;enumeration value="N2"/>
 *     &lt;enumeration value="N3"/>
 *     &lt;enumeration value="N4"/>
 *     &lt;enumeration value="N5"/>
 *     &lt;enumeration value="N6"/>
 *     &lt;enumeration value="RF"/>
 *     &lt;enumeration value="IS1"/>
 *     &lt;enumeration value="IS2"/>
 *     &lt;enumeration value="IS3"/>
 *     &lt;enumeration value="IS4"/>
 *     &lt;enumeration value="IS5"/>
 *     &lt;enumeration value="IS6"/>
 *     &lt;enumeration value="IS7"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "swathType")
@XmlEnum
public enum SwathType {

    @XmlEnumValue("S1")
    S_1("S1"),
    @XmlEnumValue("S2")
    S_2("S2"),
    @XmlEnumValue("S3")
    S_3("S3"),
    @XmlEnumValue("S4")
    S_4("S4"),
    @XmlEnumValue("S5")
    S_5("S5"),
    @XmlEnumValue("S6")
    S_6("S6"),
    IW("IW"),
    @XmlEnumValue("IW1")
    IW_1("IW1"),
    @XmlEnumValue("IW2")
    IW_2("IW2"),
    @XmlEnumValue("IW3")
    IW_3("IW3"),
    EW("EW"),
    @XmlEnumValue("EW1")
    EW_1("EW1"),
    @XmlEnumValue("EW2")
    EW_2("EW2"),
    @XmlEnumValue("EW3")
    EW_3("EW3"),
    @XmlEnumValue("EW4")
    EW_4("EW4"),
    @XmlEnumValue("EW5")
    EW_5("EW5"),
    WV("WV"),
    @XmlEnumValue("WV1")
    WV_1("WV1"),
    @XmlEnumValue("WV2")
    WV_2("WV2"),
    EN("EN"),
    @XmlEnumValue("N1")
    N_1("N1"),
    @XmlEnumValue("N2")
    N_2("N2"),
    @XmlEnumValue("N3")
    N_3("N3"),
    @XmlEnumValue("N4")
    N_4("N4"),
    @XmlEnumValue("N5")
    N_5("N5"),
    @XmlEnumValue("N6")
    N_6("N6"),
    RF("RF"),
    @XmlEnumValue("IS1")
    IS_1("IS1"),
    @XmlEnumValue("IS2")
    IS_2("IS2"),
    @XmlEnumValue("IS3")
    IS_3("IS3"),
    @XmlEnumValue("IS4")
    IS_4("IS4"),
    @XmlEnumValue("IS5")
    IS_5("IS5"),
    @XmlEnumValue("IS6")
    IS_6("IS6"),
    @XmlEnumValue("IS7")
    IS_7("IS7");
    private final String value;

    SwathType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SwathType fromValue(String v) {
        for (SwathType c: SwathType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
