//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.05 at 04:36:39 PM CET 
//


package jrc.it.annotation.reader.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Swath merging information for TOPS modes.
 * 
 * <p>Java class for swathMergeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="swathMergeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="swath" type="{}swathType"/>
 *         &lt;element name="swathBoundsList" type="{}swathBoundsListType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "swathMergeType", propOrder = {
    "swath",
    "swathBoundsList"
})
public class SwathMergeType {

    @XmlElement(required = true)
    protected SwathType swath;
    @XmlElement(required = true)
    protected SwathBoundsListType swathBoundsList;

    /**
     * Gets the value of the swath property.
     * 
     * @return
     *     possible object is
     *     {@link SwathType }
     *     
     */
    public SwathType getSwath() {
        return swath;
    }

    /**
     * Sets the value of the swath property.
     * 
     * @param value
     *     allowed object is
     *     {@link SwathType }
     *     
     */
    public void setSwath(SwathType value) {
        this.swath = value;
    }

    /**
     * Gets the value of the swathBoundsList property.
     * 
     * @return
     *     possible object is
     *     {@link SwathBoundsListType }
     *     
     */
    public SwathBoundsListType getSwathBoundsList() {
        return swathBoundsList;
    }

    /**
     * Sets the value of the swathBoundsList property.
     * 
     * @param value
     *     allowed object is
     *     {@link SwathBoundsListType }
     *     
     */
    public void setSwathBoundsList(SwathBoundsListType value) {
        this.swathBoundsList = value;
    }

}
