//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.05 at 04:36:39 PM CET 
//


package jrc.it.annotation.reader.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for bandwidthType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="bandwidthType">
 *   &lt;restriction base="{}string">
 *     &lt;enumeration value="Image"/>
 *     &lt;enumeration value="Full"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "bandwidthType")
@XmlEnum
public enum BandwidthType {

    @XmlEnumValue("Image")
    IMAGE("Image"),
    @XmlEnumValue("Full")
    FULL("Full");
    private final String value;

    BandwidthType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static BandwidthType fromValue(String v) {
        for (BandwidthType c: BandwidthType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
