//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.05 at 04:36:39 PM CET 
//


package jrc.it.annotation.reader.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Annotation record for downlink bit error counts.
 * 
 * <p>Java class for bitErrorCountType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="bitErrorCountType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="numErrSyncMarker" type="{}uint32"/>
 *         &lt;element name="numErrDataTakeId" type="{}uint32"/>
 *         &lt;element name="numErrEccNumber" type="{}uint32"/>
 *         &lt;element name="numErrTestMode" type="{}uint32"/>
 *         &lt;element name="numErrRxChannelId" type="{}uint32"/>
 *         &lt;element name="numErrInstrumentConfigId" type="{}uint32"/>
 *         &lt;element name="numErrPacketCount" type="{}uint32"/>
 *         &lt;element name="numErrPriCount" type="{}uint32"/>
 *         &lt;element name="numErrSsbErrorFlag" type="{}uint32"/>
 *         &lt;element name="numErrBaqMode" type="{}uint32"/>
 *         &lt;element name="numErrBaqBlockLength" type="{}uint32"/>
 *         &lt;element name="numErrRangeDecimation" type="{}uint32"/>
 *         &lt;element name="numErrRxGain" type="{}uint32"/>
 *         &lt;element name="numErrTxRampRate" type="{}uint32"/>
 *         &lt;element name="numErrTxPulseStartFrequency" type="{}uint32"/>
 *         &lt;element name="numErrRank" type="{}uint32"/>
 *         &lt;element name="numErrPri" type="{}uint32"/>
 *         &lt;element name="numErrSwst" type="{}uint32"/>
 *         &lt;element name="numErrSwl" type="{}uint32"/>
 *         &lt;element name="numErrPolarisation" type="{}uint32"/>
 *         &lt;element name="numErrTempComp" type="{}uint32"/>
 *         &lt;element name="numErrElevationBeamAddress" type="{}uint32"/>
 *         &lt;element name="numErrAzimuthBeamAddress" type="{}uint32"/>
 *         &lt;element name="numErrSasTestMode" type="{}uint32"/>
 *         &lt;element name="numErrCalType" type="{}uint32"/>
 *         &lt;element name="numErrCalibrationBeamAddress" type="{}uint32"/>
 *         &lt;element name="numErrCalMode" type="{}uint32"/>
 *         &lt;element name="numErrTxPulseNumber" type="{}uint32"/>
 *         &lt;element name="numErrSignalType" type="{}uint32"/>
 *         &lt;element name="numErrSwapFlag" type="{}uint32"/>
 *         &lt;element name="numErrSwathNumber" type="{}uint32"/>
 *         &lt;element name="numErrNumberOfQuads" type="{}uint32"/>
 *         &lt;element name="numIspHeaderErrors" type="{}uint32"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "bitErrorCountType", propOrder = {
    "numErrSyncMarker",
    "numErrDataTakeId",
    "numErrEccNumber",
    "numErrTestMode",
    "numErrRxChannelId",
    "numErrInstrumentConfigId",
    "numErrPacketCount",
    "numErrPriCount",
    "numErrSsbErrorFlag",
    "numErrBaqMode",
    "numErrBaqBlockLength",
    "numErrRangeDecimation",
    "numErrRxGain",
    "numErrTxRampRate",
    "numErrTxPulseStartFrequency",
    "numErrRank",
    "numErrPri",
    "numErrSwst",
    "numErrSwl",
    "numErrPolarisation",
    "numErrTempComp",
    "numErrElevationBeamAddress",
    "numErrAzimuthBeamAddress",
    "numErrSasTestMode",
    "numErrCalType",
    "numErrCalibrationBeamAddress",
    "numErrCalMode",
    "numErrTxPulseNumber",
    "numErrSignalType",
    "numErrSwapFlag",
    "numErrSwathNumber",
    "numErrNumberOfQuads",
    "numIspHeaderErrors"
})
public class BitErrorCountType {

    @XmlElement(required = true)
    protected Uint32 numErrSyncMarker;
    @XmlElement(required = true)
    protected Uint32 numErrDataTakeId;
    @XmlElement(required = true)
    protected Uint32 numErrEccNumber;
    @XmlElement(required = true)
    protected Uint32 numErrTestMode;
    @XmlElement(required = true)
    protected Uint32 numErrRxChannelId;
    @XmlElement(required = true)
    protected Uint32 numErrInstrumentConfigId;
    @XmlElement(required = true)
    protected Uint32 numErrPacketCount;
    @XmlElement(required = true)
    protected Uint32 numErrPriCount;
    @XmlElement(required = true)
    protected Uint32 numErrSsbErrorFlag;
    @XmlElement(required = true)
    protected Uint32 numErrBaqMode;
    @XmlElement(required = true)
    protected Uint32 numErrBaqBlockLength;
    @XmlElement(required = true)
    protected Uint32 numErrRangeDecimation;
    @XmlElement(required = true)
    protected Uint32 numErrRxGain;
    @XmlElement(required = true)
    protected Uint32 numErrTxRampRate;
    @XmlElement(required = true)
    protected Uint32 numErrTxPulseStartFrequency;
    @XmlElement(required = true)
    protected Uint32 numErrRank;
    @XmlElement(required = true)
    protected Uint32 numErrPri;
    @XmlElement(required = true)
    protected Uint32 numErrSwst;
    @XmlElement(required = true)
    protected Uint32 numErrSwl;
    @XmlElement(required = true)
    protected Uint32 numErrPolarisation;
    @XmlElement(required = true)
    protected Uint32 numErrTempComp;
    @XmlElement(required = true)
    protected Uint32 numErrElevationBeamAddress;
    @XmlElement(required = true)
    protected Uint32 numErrAzimuthBeamAddress;
    @XmlElement(required = true)
    protected Uint32 numErrSasTestMode;
    @XmlElement(required = true)
    protected Uint32 numErrCalType;
    @XmlElement(required = true)
    protected Uint32 numErrCalibrationBeamAddress;
    @XmlElement(required = true)
    protected Uint32 numErrCalMode;
    @XmlElement(required = true)
    protected Uint32 numErrTxPulseNumber;
    @XmlElement(required = true)
    protected Uint32 numErrSignalType;
    @XmlElement(required = true)
    protected Uint32 numErrSwapFlag;
    @XmlElement(required = true)
    protected Uint32 numErrSwathNumber;
    @XmlElement(required = true)
    protected Uint32 numErrNumberOfQuads;
    @XmlElement(required = true)
    protected Uint32 numIspHeaderErrors;

    /**
     * Gets the value of the numErrSyncMarker property.
     * 
     * @return
     *     possible object is
     *     {@link Uint32 }
     *     
     */
    public Uint32 getNumErrSyncMarker() {
        return numErrSyncMarker;
    }

    /**
     * Sets the value of the numErrSyncMarker property.
     * 
     * @param value
     *     allowed object is
     *     {@link Uint32 }
     *     
     */
    public void setNumErrSyncMarker(Uint32 value) {
        this.numErrSyncMarker = value;
    }

    /**
     * Gets the value of the numErrDataTakeId property.
     * 
     * @return
     *     possible object is
     *     {@link Uint32 }
     *     
     */
    public Uint32 getNumErrDataTakeId() {
        return numErrDataTakeId;
    }

    /**
     * Sets the value of the numErrDataTakeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Uint32 }
     *     
     */
    public void setNumErrDataTakeId(Uint32 value) {
        this.numErrDataTakeId = value;
    }

    /**
     * Gets the value of the numErrEccNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Uint32 }
     *     
     */
    public Uint32 getNumErrEccNumber() {
        return numErrEccNumber;
    }

    /**
     * Sets the value of the numErrEccNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Uint32 }
     *     
     */
    public void setNumErrEccNumber(Uint32 value) {
        this.numErrEccNumber = value;
    }

    /**
     * Gets the value of the numErrTestMode property.
     * 
     * @return
     *     possible object is
     *     {@link Uint32 }
     *     
     */
    public Uint32 getNumErrTestMode() {
        return numErrTestMode;
    }

    /**
     * Sets the value of the numErrTestMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Uint32 }
     *     
     */
    public void setNumErrTestMode(Uint32 value) {
        this.numErrTestMode = value;
    }

    /**
     * Gets the value of the numErrRxChannelId property.
     * 
     * @return
     *     possible object is
     *     {@link Uint32 }
     *     
     */
    public Uint32 getNumErrRxChannelId() {
        return numErrRxChannelId;
    }

    /**
     * Sets the value of the numErrRxChannelId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Uint32 }
     *     
     */
    public void setNumErrRxChannelId(Uint32 value) {
        this.numErrRxChannelId = value;
    }

    /**
     * Gets the value of the numErrInstrumentConfigId property.
     * 
     * @return
     *     possible object is
     *     {@link Uint32 }
     *     
     */
    public Uint32 getNumErrInstrumentConfigId() {
        return numErrInstrumentConfigId;
    }

    /**
     * Sets the value of the numErrInstrumentConfigId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Uint32 }
     *     
     */
    public void setNumErrInstrumentConfigId(Uint32 value) {
        this.numErrInstrumentConfigId = value;
    }

    /**
     * Gets the value of the numErrPacketCount property.
     * 
     * @return
     *     possible object is
     *     {@link Uint32 }
     *     
     */
    public Uint32 getNumErrPacketCount() {
        return numErrPacketCount;
    }

    /**
     * Sets the value of the numErrPacketCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Uint32 }
     *     
     */
    public void setNumErrPacketCount(Uint32 value) {
        this.numErrPacketCount = value;
    }

    /**
     * Gets the value of the numErrPriCount property.
     * 
     * @return
     *     possible object is
     *     {@link Uint32 }
     *     
     */
    public Uint32 getNumErrPriCount() {
        return numErrPriCount;
    }

    /**
     * Sets the value of the numErrPriCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Uint32 }
     *     
     */
    public void setNumErrPriCount(Uint32 value) {
        this.numErrPriCount = value;
    }

    /**
     * Gets the value of the numErrSsbErrorFlag property.
     * 
     * @return
     *     possible object is
     *     {@link Uint32 }
     *     
     */
    public Uint32 getNumErrSsbErrorFlag() {
        return numErrSsbErrorFlag;
    }

    /**
     * Sets the value of the numErrSsbErrorFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Uint32 }
     *     
     */
    public void setNumErrSsbErrorFlag(Uint32 value) {
        this.numErrSsbErrorFlag = value;
    }

    /**
     * Gets the value of the numErrBaqMode property.
     * 
     * @return
     *     possible object is
     *     {@link Uint32 }
     *     
     */
    public Uint32 getNumErrBaqMode() {
        return numErrBaqMode;
    }

    /**
     * Sets the value of the numErrBaqMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Uint32 }
     *     
     */
    public void setNumErrBaqMode(Uint32 value) {
        this.numErrBaqMode = value;
    }

    /**
     * Gets the value of the numErrBaqBlockLength property.
     * 
     * @return
     *     possible object is
     *     {@link Uint32 }
     *     
     */
    public Uint32 getNumErrBaqBlockLength() {
        return numErrBaqBlockLength;
    }

    /**
     * Sets the value of the numErrBaqBlockLength property.
     * 
     * @param value
     *     allowed object is
     *     {@link Uint32 }
     *     
     */
    public void setNumErrBaqBlockLength(Uint32 value) {
        this.numErrBaqBlockLength = value;
    }

    /**
     * Gets the value of the numErrRangeDecimation property.
     * 
     * @return
     *     possible object is
     *     {@link Uint32 }
     *     
     */
    public Uint32 getNumErrRangeDecimation() {
        return numErrRangeDecimation;
    }

    /**
     * Sets the value of the numErrRangeDecimation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Uint32 }
     *     
     */
    public void setNumErrRangeDecimation(Uint32 value) {
        this.numErrRangeDecimation = value;
    }

    /**
     * Gets the value of the numErrRxGain property.
     * 
     * @return
     *     possible object is
     *     {@link Uint32 }
     *     
     */
    public Uint32 getNumErrRxGain() {
        return numErrRxGain;
    }

    /**
     * Sets the value of the numErrRxGain property.
     * 
     * @param value
     *     allowed object is
     *     {@link Uint32 }
     *     
     */
    public void setNumErrRxGain(Uint32 value) {
        this.numErrRxGain = value;
    }

    /**
     * Gets the value of the numErrTxRampRate property.
     * 
     * @return
     *     possible object is
     *     {@link Uint32 }
     *     
     */
    public Uint32 getNumErrTxRampRate() {
        return numErrTxRampRate;
    }

    /**
     * Sets the value of the numErrTxRampRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Uint32 }
     *     
     */
    public void setNumErrTxRampRate(Uint32 value) {
        this.numErrTxRampRate = value;
    }

    /**
     * Gets the value of the numErrTxPulseStartFrequency property.
     * 
     * @return
     *     possible object is
     *     {@link Uint32 }
     *     
     */
    public Uint32 getNumErrTxPulseStartFrequency() {
        return numErrTxPulseStartFrequency;
    }

    /**
     * Sets the value of the numErrTxPulseStartFrequency property.
     * 
     * @param value
     *     allowed object is
     *     {@link Uint32 }
     *     
     */
    public void setNumErrTxPulseStartFrequency(Uint32 value) {
        this.numErrTxPulseStartFrequency = value;
    }

    /**
     * Gets the value of the numErrRank property.
     * 
     * @return
     *     possible object is
     *     {@link Uint32 }
     *     
     */
    public Uint32 getNumErrRank() {
        return numErrRank;
    }

    /**
     * Sets the value of the numErrRank property.
     * 
     * @param value
     *     allowed object is
     *     {@link Uint32 }
     *     
     */
    public void setNumErrRank(Uint32 value) {
        this.numErrRank = value;
    }

    /**
     * Gets the value of the numErrPri property.
     * 
     * @return
     *     possible object is
     *     {@link Uint32 }
     *     
     */
    public Uint32 getNumErrPri() {
        return numErrPri;
    }

    /**
     * Sets the value of the numErrPri property.
     * 
     * @param value
     *     allowed object is
     *     {@link Uint32 }
     *     
     */
    public void setNumErrPri(Uint32 value) {
        this.numErrPri = value;
    }

    /**
     * Gets the value of the numErrSwst property.
     * 
     * @return
     *     possible object is
     *     {@link Uint32 }
     *     
     */
    public Uint32 getNumErrSwst() {
        return numErrSwst;
    }

    /**
     * Sets the value of the numErrSwst property.
     * 
     * @param value
     *     allowed object is
     *     {@link Uint32 }
     *     
     */
    public void setNumErrSwst(Uint32 value) {
        this.numErrSwst = value;
    }

    /**
     * Gets the value of the numErrSwl property.
     * 
     * @return
     *     possible object is
     *     {@link Uint32 }
     *     
     */
    public Uint32 getNumErrSwl() {
        return numErrSwl;
    }

    /**
     * Sets the value of the numErrSwl property.
     * 
     * @param value
     *     allowed object is
     *     {@link Uint32 }
     *     
     */
    public void setNumErrSwl(Uint32 value) {
        this.numErrSwl = value;
    }

    /**
     * Gets the value of the numErrPolarisation property.
     * 
     * @return
     *     possible object is
     *     {@link Uint32 }
     *     
     */
    public Uint32 getNumErrPolarisation() {
        return numErrPolarisation;
    }

    /**
     * Sets the value of the numErrPolarisation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Uint32 }
     *     
     */
    public void setNumErrPolarisation(Uint32 value) {
        this.numErrPolarisation = value;
    }

    /**
     * Gets the value of the numErrTempComp property.
     * 
     * @return
     *     possible object is
     *     {@link Uint32 }
     *     
     */
    public Uint32 getNumErrTempComp() {
        return numErrTempComp;
    }

    /**
     * Sets the value of the numErrTempComp property.
     * 
     * @param value
     *     allowed object is
     *     {@link Uint32 }
     *     
     */
    public void setNumErrTempComp(Uint32 value) {
        this.numErrTempComp = value;
    }

    /**
     * Gets the value of the numErrElevationBeamAddress property.
     * 
     * @return
     *     possible object is
     *     {@link Uint32 }
     *     
     */
    public Uint32 getNumErrElevationBeamAddress() {
        return numErrElevationBeamAddress;
    }

    /**
     * Sets the value of the numErrElevationBeamAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link Uint32 }
     *     
     */
    public void setNumErrElevationBeamAddress(Uint32 value) {
        this.numErrElevationBeamAddress = value;
    }

    /**
     * Gets the value of the numErrAzimuthBeamAddress property.
     * 
     * @return
     *     possible object is
     *     {@link Uint32 }
     *     
     */
    public Uint32 getNumErrAzimuthBeamAddress() {
        return numErrAzimuthBeamAddress;
    }

    /**
     * Sets the value of the numErrAzimuthBeamAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link Uint32 }
     *     
     */
    public void setNumErrAzimuthBeamAddress(Uint32 value) {
        this.numErrAzimuthBeamAddress = value;
    }

    /**
     * Gets the value of the numErrSasTestMode property.
     * 
     * @return
     *     possible object is
     *     {@link Uint32 }
     *     
     */
    public Uint32 getNumErrSasTestMode() {
        return numErrSasTestMode;
    }

    /**
     * Sets the value of the numErrSasTestMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Uint32 }
     *     
     */
    public void setNumErrSasTestMode(Uint32 value) {
        this.numErrSasTestMode = value;
    }

    /**
     * Gets the value of the numErrCalType property.
     * 
     * @return
     *     possible object is
     *     {@link Uint32 }
     *     
     */
    public Uint32 getNumErrCalType() {
        return numErrCalType;
    }

    /**
     * Sets the value of the numErrCalType property.
     * 
     * @param value
     *     allowed object is
     *     {@link Uint32 }
     *     
     */
    public void setNumErrCalType(Uint32 value) {
        this.numErrCalType = value;
    }

    /**
     * Gets the value of the numErrCalibrationBeamAddress property.
     * 
     * @return
     *     possible object is
     *     {@link Uint32 }
     *     
     */
    public Uint32 getNumErrCalibrationBeamAddress() {
        return numErrCalibrationBeamAddress;
    }

    /**
     * Sets the value of the numErrCalibrationBeamAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link Uint32 }
     *     
     */
    public void setNumErrCalibrationBeamAddress(Uint32 value) {
        this.numErrCalibrationBeamAddress = value;
    }

    /**
     * Gets the value of the numErrCalMode property.
     * 
     * @return
     *     possible object is
     *     {@link Uint32 }
     *     
     */
    public Uint32 getNumErrCalMode() {
        return numErrCalMode;
    }

    /**
     * Sets the value of the numErrCalMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Uint32 }
     *     
     */
    public void setNumErrCalMode(Uint32 value) {
        this.numErrCalMode = value;
    }

    /**
     * Gets the value of the numErrTxPulseNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Uint32 }
     *     
     */
    public Uint32 getNumErrTxPulseNumber() {
        return numErrTxPulseNumber;
    }

    /**
     * Sets the value of the numErrTxPulseNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Uint32 }
     *     
     */
    public void setNumErrTxPulseNumber(Uint32 value) {
        this.numErrTxPulseNumber = value;
    }

    /**
     * Gets the value of the numErrSignalType property.
     * 
     * @return
     *     possible object is
     *     {@link Uint32 }
     *     
     */
    public Uint32 getNumErrSignalType() {
        return numErrSignalType;
    }

    /**
     * Sets the value of the numErrSignalType property.
     * 
     * @param value
     *     allowed object is
     *     {@link Uint32 }
     *     
     */
    public void setNumErrSignalType(Uint32 value) {
        this.numErrSignalType = value;
    }

    /**
     * Gets the value of the numErrSwapFlag property.
     * 
     * @return
     *     possible object is
     *     {@link Uint32 }
     *     
     */
    public Uint32 getNumErrSwapFlag() {
        return numErrSwapFlag;
    }

    /**
     * Sets the value of the numErrSwapFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Uint32 }
     *     
     */
    public void setNumErrSwapFlag(Uint32 value) {
        this.numErrSwapFlag = value;
    }

    /**
     * Gets the value of the numErrSwathNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Uint32 }
     *     
     */
    public Uint32 getNumErrSwathNumber() {
        return numErrSwathNumber;
    }

    /**
     * Sets the value of the numErrSwathNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Uint32 }
     *     
     */
    public void setNumErrSwathNumber(Uint32 value) {
        this.numErrSwathNumber = value;
    }

    /**
     * Gets the value of the numErrNumberOfQuads property.
     * 
     * @return
     *     possible object is
     *     {@link Uint32 }
     *     
     */
    public Uint32 getNumErrNumberOfQuads() {
        return numErrNumberOfQuads;
    }

    /**
     * Sets the value of the numErrNumberOfQuads property.
     * 
     * @param value
     *     allowed object is
     *     {@link Uint32 }
     *     
     */
    public void setNumErrNumberOfQuads(Uint32 value) {
        this.numErrNumberOfQuads = value;
    }

    /**
     * Gets the value of the numIspHeaderErrors property.
     * 
     * @return
     *     possible object is
     *     {@link Uint32 }
     *     
     */
    public Uint32 getNumIspHeaderErrors() {
        return numIspHeaderErrors;
    }

    /**
     * Sets the value of the numIspHeaderErrors property.
     * 
     * @param value
     *     allowed object is
     *     {@link Uint32 }
     *     
     */
    public void setNumIspHeaderErrors(Uint32 value) {
        this.numIspHeaderErrors = value;
    }

}
