//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.05 at 04:36:39 PM CET 
//


package jrc.it.annotation.reader.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Annotation record for a geolocation grid point.
 * 
 * <p>Java class for geolocationGridPointType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="geolocationGridPointType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="azimuthTime" type="{}timeType"/>
 *         &lt;element name="slantRangeTime" type="{}double"/>
 *         &lt;element name="line" type="{}uint32"/>
 *         &lt;element name="pixel" type="{}uint32"/>
 *         &lt;element name="latitude" type="{}double"/>
 *         &lt;element name="longitude" type="{}double"/>
 *         &lt;element name="height" type="{}double"/>
 *         &lt;element name="incidenceAngle" type="{}double"/>
 *         &lt;element name="elevationAngle" type="{}double"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "geolocationGridPointType", propOrder = {
    "azimuthTime",
    "slantRangeTime",
    "line",
    "pixel",
    "latitude",
    "longitude",
    "height",
    "incidenceAngle",
    "elevationAngle"
})
public class GeolocationGridPointType {

    @XmlElement(required = true)
    protected XMLGregorianCalendar azimuthTime;
    @XmlElement(required = true)
    protected Double slantRangeTime;
    @XmlElement(required = true)
    protected Uint32 line;
    @XmlElement(required = true)
    protected Uint32 pixel;
    @XmlElement(required = true)
    protected Double latitude;
    @XmlElement(required = true)
    protected Double longitude;
    @XmlElement(required = true)
    protected Double height;
    @XmlElement(required = true)
    protected Double incidenceAngle;
    @XmlElement(required = true)
    protected Double elevationAngle;

    /**
     * Gets the value of the azimuthTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getAzimuthTime() {
        return azimuthTime;
    }

    /**
     * Sets the value of the azimuthTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAzimuthTime(XMLGregorianCalendar value) {
        this.azimuthTime = value;
    }

    /**
     * Gets the value of the slantRangeTime property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getSlantRangeTime() {
        return slantRangeTime;
    }

    /**
     * Sets the value of the slantRangeTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setSlantRangeTime(Double value) {
        this.slantRangeTime = value;
    }

    /**
     * Gets the value of the line property.
     * 
     * @return
     *     possible object is
     *     {@link Uint32 }
     *     
     */
    public Uint32 getLine() {
        return line;
    }

    /**
     * Sets the value of the line property.
     * 
     * @param value
     *     allowed object is
     *     {@link Uint32 }
     *     
     */
    public void setLine(Uint32 value) {
        this.line = value;
    }

    /**
     * Gets the value of the pixel property.
     * 
     * @return
     *     possible object is
     *     {@link Uint32 }
     *     
     */
    public Uint32 getPixel() {
        return pixel;
    }

    /**
     * Sets the value of the pixel property.
     * 
     * @param value
     *     allowed object is
     *     {@link Uint32 }
     *     
     */
    public void setPixel(Uint32 value) {
        this.pixel = value;
    }

    /**
     * Gets the value of the latitude property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getLatitude() {
        return latitude;
    }

    /**
     * Sets the value of the latitude property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setLatitude(Double value) {
        this.latitude = value;
    }

    /**
     * Gets the value of the longitude property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getLongitude() {
        return longitude;
    }

    /**
     * Sets the value of the longitude property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setLongitude(Double value) {
        this.longitude = value;
    }

    /**
     * Gets the value of the height property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getHeight() {
        return height;
    }

    /**
     * Sets the value of the height property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setHeight(Double value) {
        this.height = value;
    }

    /**
     * Gets the value of the incidenceAngle property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getIncidenceAngle() {
        return incidenceAngle;
    }

    /**
     * Sets the value of the incidenceAngle property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setIncidenceAngle(Double value) {
        this.incidenceAngle = value;
    }

    /**
     * Gets the value of the elevationAngle property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getElevationAngle() {
        return elevationAngle;
    }

    /**
     * Sets the value of the elevationAngle property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setElevationAngle(Double value) {
        this.elevationAngle = value;
    }

}
