//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.05 at 04:36:39 PM CET 
//


package jrc.it.annotation.reader.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Annotation record for image dimension information.
 * 
 * <p>Java class for inputDimensionsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="inputDimensionsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="azimuthTime" type="{}timeType"/>
 *         &lt;element name="swath" type="{}swathType"/>
 *         &lt;element name="numberOfInputSamples" type="{}uint32"/>
 *         &lt;element name="numberOfInputLines" type="{}uint32"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "inputDimensionsType", propOrder = {
    "azimuthTime",
    "swath",
    "numberOfInputSamples",
    "numberOfInputLines"
})
public class InputDimensionsType {

    @XmlElement(required = true)
    protected XMLGregorianCalendar azimuthTime;
    @XmlElement(required = true)
    protected SwathType swath;
    @XmlElement(required = true)
    protected Uint32 numberOfInputSamples;
    @XmlElement(required = true)
    protected Uint32 numberOfInputLines;

    /**
     * Gets the value of the azimuthTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getAzimuthTime() {
        return azimuthTime;
    }

    /**
     * Sets the value of the azimuthTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAzimuthTime(XMLGregorianCalendar value) {
        this.azimuthTime = value;
    }

    /**
     * Gets the value of the swath property.
     * 
     * @return
     *     possible object is
     *     {@link SwathType }
     *     
     */
    public SwathType getSwath() {
        return swath;
    }

    /**
     * Sets the value of the swath property.
     * 
     * @param value
     *     allowed object is
     *     {@link SwathType }
     *     
     */
    public void setSwath(SwathType value) {
        this.swath = value;
    }

    /**
     * Gets the value of the numberOfInputSamples property.
     * 
     * @return
     *     possible object is
     *     {@link Uint32 }
     *     
     */
    public Uint32 getNumberOfInputSamples() {
        return numberOfInputSamples;
    }

    /**
     * Sets the value of the numberOfInputSamples property.
     * 
     * @param value
     *     allowed object is
     *     {@link Uint32 }
     *     
     */
    public void setNumberOfInputSamples(Uint32 value) {
        this.numberOfInputSamples = value;
    }

    /**
     * Gets the value of the numberOfInputLines property.
     * 
     * @return
     *     possible object is
     *     {@link Uint32 }
     *     
     */
    public Uint32 getNumberOfInputLines() {
        return numberOfInputLines;
    }

    /**
     * Sets the value of the numberOfInputLines property.
     * 
     * @param value
     *     allowed object is
     *     {@link Uint32 }
     *     
     */
    public void setNumberOfInputLines(Uint32 value) {
        this.numberOfInputLines = value;
    }

}
