//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.05 at 04:36:39 PM CET 
//


package jrc.it.annotation.reader.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Swath merging information for IW mode.
 * 
 * <p>Java class for iwMergeInformationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="iwMergeInformationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="iw1" type="{}swathBoundsListType"/>
 *         &lt;element name="iw2" type="{}swathBoundsListType"/>
 *         &lt;element name="iw3" type="{}swathBoundsListType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "iwMergeInformationType", propOrder = {
    "iw1",
    "iw2",
    "iw3"
})
public class IwMergeInformationType {

    @XmlElement(required = true)
    protected SwathBoundsListType iw1;
    @XmlElement(required = true)
    protected SwathBoundsListType iw2;
    @XmlElement(required = true)
    protected SwathBoundsListType iw3;

    /**
     * Gets the value of the iw1 property.
     * 
     * @return
     *     possible object is
     *     {@link SwathBoundsListType }
     *     
     */
    public SwathBoundsListType getIw1() {
        return iw1;
    }

    /**
     * Sets the value of the iw1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link SwathBoundsListType }
     *     
     */
    public void setIw1(SwathBoundsListType value) {
        this.iw1 = value;
    }

    /**
     * Gets the value of the iw2 property.
     * 
     * @return
     *     possible object is
     *     {@link SwathBoundsListType }
     *     
     */
    public SwathBoundsListType getIw2() {
        return iw2;
    }

    /**
     * Sets the value of the iw2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link SwathBoundsListType }
     *     
     */
    public void setIw2(SwathBoundsListType value) {
        this.iw2 = value;
    }

    /**
     * Gets the value of the iw3 property.
     * 
     * @return
     *     possible object is
     *     {@link SwathBoundsListType }
     *     
     */
    public SwathBoundsListType getIw3() {
        return iw3;
    }

    /**
     * Sets the value of the iw3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link SwathBoundsListType }
     *     
     */
    public void setIw3(SwathBoundsListType value) {
        this.iw3 = value;
    }

}
