//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.05 at 04:36:39 PM CET 
//


package jrc.it.annotation.reader.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Annotation record for Sentinel-1 level 1 geolocation grid annotations.
 * 
 * <p>Java class for l1GeolocationGridType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="l1GeolocationGridType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="geolocationGridPointList" type="{}geolocationGridPointListType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "l1GeolocationGridType", propOrder = {
    "geolocationGridPointList"
})
public class L1GeolocationGridType {

    @XmlElement(required = true)
    protected GeolocationGridPointListType geolocationGridPointList;

    /**
     * Gets the value of the geolocationGridPointList property.
     * 
     * @return
     *     possible object is
     *     {@link GeolocationGridPointListType }
     *     
     */
    public GeolocationGridPointListType getGeolocationGridPointList() {
        return geolocationGridPointList;
    }

    /**
     * Sets the value of the geolocationGridPointList property.
     * 
     * @param value
     *     allowed object is
     *     {@link GeolocationGridPointListType }
     *     
     */
    public void setGeolocationGridPointList(GeolocationGridPointListType value) {
        this.geolocationGridPointList = value;
    }

}
