//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.05 at 04:36:39 PM CET 
//


package jrc.it.annotation.reader.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Annotation record for Sentinel-1 level 1 image product annotations.
 * 
 * <p>Java class for l1ImageAnnotationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="l1ImageAnnotationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="imageInformation" type="{}imageInformationType"/>
 *         &lt;element name="processingInformation" type="{}processingInformationType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "l1ImageAnnotationType", propOrder = {
    "imageInformation",
    "processingInformation"
})
public class L1ImageAnnotationType {

    @XmlElement(required = true)
    protected ImageInformationType imageInformation;
    @XmlElement(required = true)
    protected ProcessingInformationType processingInformation;

    /**
     * Gets the value of the imageInformation property.
     * 
     * @return
     *     possible object is
     *     {@link ImageInformationType }
     *     
     */
    public ImageInformationType getImageInformation() {
        return imageInformation;
    }

    /**
     * Sets the value of the imageInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImageInformationType }
     *     
     */
    public void setImageInformation(ImageInformationType value) {
        this.imageInformation = value;
    }

    /**
     * Gets the value of the processingInformation property.
     * 
     * @return
     *     possible object is
     *     {@link ProcessingInformationType }
     *     
     */
    public ProcessingInformationType getProcessingInformation() {
        return processingInformation;
    }

    /**
     * Sets the value of the processingInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProcessingInformationType }
     *     
     */
    public void setProcessingInformation(ProcessingInformationType value) {
        this.processingInformation = value;
    }

}
