//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.05 at 04:36:39 PM CET 
//


package jrc.it.annotation.reader.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Annotation record for Sentinel-1 level 1 quality summary annotations.
 * 
 * <p>Java class for l1QualityInformationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="l1QualityInformationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="productQualityIndex" type="{}double"/>
 *         &lt;element name="qualityDataList" type="{}qualityDataListType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "l1QualityInformationType", propOrder = {
    "productQualityIndex",
    "qualityDataList"
})
public class L1QualityInformationType {

    @XmlElement(required = true)
    protected Double productQualityIndex;
    @XmlElement(required = true)
    protected QualityDataListType qualityDataList;

    /**
     * Gets the value of the productQualityIndex property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getProductQualityIndex() {
        return productQualityIndex;
    }

    /**
     * Sets the value of the productQualityIndex property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setProductQualityIndex(Double value) {
        this.productQualityIndex = value;
    }

    /**
     * Gets the value of the qualityDataList property.
     * 
     * @return
     *     possible object is
     *     {@link QualityDataListType }
     *     
     */
    public QualityDataListType getQualityDataList() {
        return qualityDataList;
    }

    /**
     * Sets the value of the qualityDataList property.
     * 
     * @param value
     *     allowed object is
     *     {@link QualityDataListType }
     *     
     */
    public void setQualityDataList(QualityDataListType value) {
        this.qualityDataList = value;
    }

}
