//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.05 at 04:36:39 PM CET 
//


package jrc.it.annotation.reader.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for rrfSpectrumType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="rrfSpectrumType">
 *   &lt;restriction base="{}string">
 *     &lt;enumeration value="Unextended"/>
 *     &lt;enumeration value="Extended Flat"/>
 *     &lt;enumeration value="Extended Tapered"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "rrfSpectrumType")
@XmlEnum
public enum RrfSpectrumType {

    @XmlEnumValue("Unextended")
    UNEXTENDED("Unextended"),
    @XmlEnumValue("Extended Flat")
    EXTENDED_FLAT("Extended Flat"),
    @XmlEnumValue("Extended Tapered")
    EXTENDED_TAPERED("Extended Tapered");
    private final String value;

    RrfSpectrumType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static RrfSpectrumType fromValue(String v) {
        for (RrfSpectrumType c: RrfSpectrumType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
