/*
 * SimpleEditorDialog.java
 *
 * Created on April 9, 2008, 8:51 AM
 */
package org.geoimage.viewer.widget;

import org.geoimage.viewer.core.api.IEditable;
import org.geoimage.viewer.core.api.ILayer;

/**
 *
 * @author  thoorfr
 */
public class SimpleEditorDialog extends javax.swing.JDialog {

    private IEditable layer;

    /** Creates new form SimpleEditorDialog */
    public SimpleEditorDialog(java.awt.Frame parent, boolean modal, IEditable layer) {
        super(parent, modal);
        initComponents();
        this.layer = layer;
        setTitle(((ILayer) this.layer).getName());
    }

    @Override
    public void dispose() {
        this.setVisible(false);
        super.dispose();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        addButton = new javax.swing.JToggleButton();
        delButton = new javax.swing.JToggleButton();
        moveButton = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 4));

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        getContentPane().add(addButton);

        delButton.setText("Del");
        delButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delButtonActionPerformed(evt);
            }
        });
        getContentPane().add(delButton);

        moveButton.setText("Move");
        moveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveButtonActionPerformed(evt);
            }
        });
        getContentPane().add(moveButton);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        if (addButton.isSelected()) {
            delButton.setSelected(false);
            moveButton.setSelected(false);
        }
        this.layer.setAddAction(addButton.isSelected());
    }//GEN-LAST:event_addButtonActionPerformed

    private void delButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delButtonActionPerformed
        if (delButton.isSelected()) {
            addButton.setSelected(false);
            moveButton.setSelected(false);
        }
        this.layer.setDeleteAction(delButton.isSelected());
    }//GEN-LAST:event_delButtonActionPerformed

    private void moveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveButtonActionPerformed
        if (moveButton.isSelected()) {
            delButton.setSelected(false);
            addButton.setSelected(false);
        }
        this.layer.setMoveAction(moveButton.isSelected());
    }//GEN-LAST:event_moveButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton addButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JToggleButton delButton;
    private javax.swing.JToggleButton moveButton;
    // End of variables declaration//GEN-END:variables
}
