//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.24 at 04:43:09 PM CEST 
//


package safe.annotation;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}imageStatistics"/>
 *         &lt;element ref="{}outputDataMeanOutsideNominalRangeFlag"/>
 *         &lt;element ref="{}outputDataStDevOutsideNominalRangeFlag"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "imageStatistics",
    "outputDataMeanOutsideNominalRangeFlag",
    "outputDataStDevOutsideNominalRangeFlag"
})
@XmlRootElement(name = "imageQuality")
public class ImageQuality {

    @XmlElement(required = true)
    protected ImageStatistics imageStatistics;
    protected boolean outputDataMeanOutsideNominalRangeFlag;
    protected boolean outputDataStDevOutsideNominalRangeFlag;

    /**
     * Gets the value of the imageStatistics property.
     * 
     * @return
     *     possible object is
     *     {@link ImageStatistics }
     *     
     */
    public ImageStatistics getImageStatistics() {
        return imageStatistics;
    }

    /**
     * Sets the value of the imageStatistics property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImageStatistics }
     *     
     */
    public void setImageStatistics(ImageStatistics value) {
        this.imageStatistics = value;
    }

    /**
     * Gets the value of the outputDataMeanOutsideNominalRangeFlag property.
     * 
     */
    public boolean isOutputDataMeanOutsideNominalRangeFlag() {
        return outputDataMeanOutsideNominalRangeFlag;
    }

    /**
     * Sets the value of the outputDataMeanOutsideNominalRangeFlag property.
     * 
     */
    public void setOutputDataMeanOutsideNominalRangeFlag(boolean value) {
        this.outputDataMeanOutsideNominalRangeFlag = value;
    }

    /**
     * Gets the value of the outputDataStDevOutsideNominalRangeFlag property.
     * 
     */
    public boolean isOutputDataStDevOutsideNominalRangeFlag() {
        return outputDataStDevOutsideNominalRangeFlag;
    }

    /**
     * Sets the value of the outputDataStDevOutsideNominalRangeFlag property.
     * 
     */
    public void setOutputDataStDevOutsideNominalRangeFlag(boolean value) {
        this.outputDataStDevOutsideNominalRangeFlag = value;
    }

}
