//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.24 at 04:43:09 PM CEST 
//


package safe.annotation;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}iBiasUpperBound"/>
 *         &lt;element ref="{}iBiasLowerBound"/>
 *         &lt;element ref="{}qBiasUpperBound"/>
 *         &lt;element ref="{}qBiasLowerBound"/>
 *         &lt;element ref="{}iqGainUpperBound"/>
 *         &lt;element ref="{}iqGainLowerBound"/>
 *         &lt;element ref="{}iqQuadratureDepartureUpperBound"/>
 *         &lt;element ref="{}iqQuadratureDepartureLowerBound"/>
 *         &lt;element ref="{}iBiasUsedForCorrection"/>
 *         &lt;element ref="{}qBiasUsedForCorrection"/>
 *         &lt;element ref="{}iqGainImbalanceUsedForCorrection"/>
 *         &lt;element ref="{}iqQuadratureDepartureUsedForCorrection"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "iBiasUpperBound",
    "iBiasLowerBound",
    "qBiasUpperBound",
    "qBiasLowerBound",
    "iqGainUpperBound",
    "iqGainLowerBound",
    "iqQuadratureDepartureUpperBound",
    "iqQuadratureDepartureLowerBound",
    "iBiasUsedForCorrection",
    "qBiasUsedForCorrection",
    "iqGainImbalanceUsedForCorrection",
    "iqQuadratureDepartureUsedForCorrection"
})
@XmlRootElement(name = "support")
public class Support {

    protected double iBiasUpperBound;
    protected double iBiasLowerBound;
    protected double qBiasUpperBound;
    protected double qBiasLowerBound;
    protected double iqGainUpperBound;
    protected double iqGainLowerBound;
    protected double iqQuadratureDepartureUpperBound;
    protected double iqQuadratureDepartureLowerBound;
    protected double iBiasUsedForCorrection;
    protected double qBiasUsedForCorrection;
    protected double iqGainImbalanceUsedForCorrection;
    protected double iqQuadratureDepartureUsedForCorrection;

    /**
     * Gets the value of the iBiasUpperBound property.
     * 
     */
    public double getIBiasUpperBound() {
        return iBiasUpperBound;
    }

    /**
     * Sets the value of the iBiasUpperBound property.
     * 
     */
    public void setIBiasUpperBound(double value) {
        this.iBiasUpperBound = value;
    }

    /**
     * Gets the value of the iBiasLowerBound property.
     * 
     */
    public double getIBiasLowerBound() {
        return iBiasLowerBound;
    }

    /**
     * Sets the value of the iBiasLowerBound property.
     * 
     */
    public void setIBiasLowerBound(double value) {
        this.iBiasLowerBound = value;
    }

    /**
     * Gets the value of the qBiasUpperBound property.
     * 
     */
    public double getQBiasUpperBound() {
        return qBiasUpperBound;
    }

    /**
     * Sets the value of the qBiasUpperBound property.
     * 
     */
    public void setQBiasUpperBound(double value) {
        this.qBiasUpperBound = value;
    }

    /**
     * Gets the value of the qBiasLowerBound property.
     * 
     */
    public double getQBiasLowerBound() {
        return qBiasLowerBound;
    }

    /**
     * Sets the value of the qBiasLowerBound property.
     * 
     */
    public void setQBiasLowerBound(double value) {
        this.qBiasLowerBound = value;
    }

    /**
     * Gets the value of the iqGainUpperBound property.
     * 
     */
    public double getIqGainUpperBound() {
        return iqGainUpperBound;
    }

    /**
     * Sets the value of the iqGainUpperBound property.
     * 
     */
    public void setIqGainUpperBound(double value) {
        this.iqGainUpperBound = value;
    }

    /**
     * Gets the value of the iqGainLowerBound property.
     * 
     */
    public double getIqGainLowerBound() {
        return iqGainLowerBound;
    }

    /**
     * Sets the value of the iqGainLowerBound property.
     * 
     */
    public void setIqGainLowerBound(double value) {
        this.iqGainLowerBound = value;
    }

    /**
     * Gets the value of the iqQuadratureDepartureUpperBound property.
     * 
     */
    public double getIqQuadratureDepartureUpperBound() {
        return iqQuadratureDepartureUpperBound;
    }

    /**
     * Sets the value of the iqQuadratureDepartureUpperBound property.
     * 
     */
    public void setIqQuadratureDepartureUpperBound(double value) {
        this.iqQuadratureDepartureUpperBound = value;
    }

    /**
     * Gets the value of the iqQuadratureDepartureLowerBound property.
     * 
     */
    public double getIqQuadratureDepartureLowerBound() {
        return iqQuadratureDepartureLowerBound;
    }

    /**
     * Sets the value of the iqQuadratureDepartureLowerBound property.
     * 
     */
    public void setIqQuadratureDepartureLowerBound(double value) {
        this.iqQuadratureDepartureLowerBound = value;
    }

    /**
     * Gets the value of the iBiasUsedForCorrection property.
     * 
     */
    public double getIBiasUsedForCorrection() {
        return iBiasUsedForCorrection;
    }

    /**
     * Sets the value of the iBiasUsedForCorrection property.
     * 
     */
    public void setIBiasUsedForCorrection(double value) {
        this.iBiasUsedForCorrection = value;
    }

    /**
     * Gets the value of the qBiasUsedForCorrection property.
     * 
     */
    public double getQBiasUsedForCorrection() {
        return qBiasUsedForCorrection;
    }

    /**
     * Sets the value of the qBiasUsedForCorrection property.
     * 
     */
    public void setQBiasUsedForCorrection(double value) {
        this.qBiasUsedForCorrection = value;
    }

    /**
     * Gets the value of the iqGainImbalanceUsedForCorrection property.
     * 
     */
    public double getIqGainImbalanceUsedForCorrection() {
        return iqGainImbalanceUsedForCorrection;
    }

    /**
     * Sets the value of the iqGainImbalanceUsedForCorrection property.
     * 
     */
    public void setIqGainImbalanceUsedForCorrection(double value) {
        this.iqGainImbalanceUsedForCorrection = value;
    }

    /**
     * Gets the value of the iqQuadratureDepartureUsedForCorrection property.
     * 
     */
    public double getIqQuadratureDepartureUsedForCorrection() {
        return iqQuadratureDepartureUsedForCorrection;
    }

    /**
     * Sets the value of the iqQuadratureDepartureUsedForCorrection property.
     * 
     */
    public void setIqQuadratureDepartureUsedForCorrection(double value) {
        this.iqQuadratureDepartureUsedForCorrection = value;
    }

}
