//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.24 at 04:43:09 PM CEST 
//


package safe.annotation;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}windowType"/>
 *         &lt;element ref="{}windowCoefficient"/>
 *         &lt;element ref="{}totalBandwidth"/>
 *         &lt;element ref="{}processingBandwidth"/>
 *         &lt;element ref="{}lookBandwidth"/>
 *         &lt;element ref="{}numberOfLooks"/>
 *         &lt;element ref="{}lookOverlap"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "windowType",
    "windowCoefficient",
    "totalBandwidth",
    "processingBandwidth",
    "lookBandwidth",
    "numberOfLooks",
    "lookOverlap"
})
@XmlRootElement(name = "azimuthProcessing")
public class AzimuthProcessing {

    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String windowType;
    protected double windowCoefficient;
    protected double totalBandwidth;
    protected double processingBandwidth;
    protected double lookBandwidth;
    @XmlElement(required = true)
    protected BigInteger numberOfLooks;
    protected double lookOverlap;

    /**
     * Gets the value of the windowType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWindowType() {
        return windowType;
    }

    /**
     * Sets the value of the windowType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWindowType(String value) {
        this.windowType = value;
    }

    /**
     * Gets the value of the windowCoefficient property.
     * 
     */
    public double getWindowCoefficient() {
        return windowCoefficient;
    }

    /**
     * Sets the value of the windowCoefficient property.
     * 
     */
    public void setWindowCoefficient(double value) {
        this.windowCoefficient = value;
    }

    /**
     * Gets the value of the totalBandwidth property.
     * 
     */
    public double getTotalBandwidth() {
        return totalBandwidth;
    }

    /**
     * Sets the value of the totalBandwidth property.
     * 
     */
    public void setTotalBandwidth(double value) {
        this.totalBandwidth = value;
    }

    /**
     * Gets the value of the processingBandwidth property.
     * 
     */
    public double getProcessingBandwidth() {
        return processingBandwidth;
    }

    /**
     * Sets the value of the processingBandwidth property.
     * 
     */
    public void setProcessingBandwidth(double value) {
        this.processingBandwidth = value;
    }

    /**
     * Gets the value of the lookBandwidth property.
     * 
     */
    public double getLookBandwidth() {
        return lookBandwidth;
    }

    /**
     * Sets the value of the lookBandwidth property.
     * 
     */
    public void setLookBandwidth(double value) {
        this.lookBandwidth = value;
    }

    /**
     * Gets the value of the numberOfLooks property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumberOfLooks() {
        return numberOfLooks;
    }

    /**
     * Sets the value of the numberOfLooks property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumberOfLooks(BigInteger value) {
        this.numberOfLooks = value;
    }

    /**
     * Gets the value of the lookOverlap property.
     * 
     */
    public double getLookOverlap() {
        return lookOverlap;
    }

    /**
     * Sets the value of the lookOverlap property.
     * 
     */
    public void setLookOverlap(double value) {
        this.lookOverlap = value;
    }

}
